import * as Base from './engine.js';
import { generateStaff, rng } from './generator.js';
import { hashString, primeraFederacionClubs } from '../data/clubs.js';
import { sponsorRights, facilityDefs, maxLevel } from '../data/management.js';

const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
const START_DATE='2026-08-10';
const DAY_MS=86400000;
const staffRoleMap={
  'Médico jefe':'chiefDoctor','Fisioterapeuta jefe':'physio','Jefe de scouting nacional':'nationalScout','Jefe de scouting internacional':'internationalScout','Jefe de scouting de cantera':'youthScout','Director de cantera':'academyDirector','Preparador físico':'fitnessCoach','Preparador de porteros':'keeperCoach','Segundo entrenador':'assistantCoach','Director deportivo':'sportingDirector','Chief Merchandising Officer':'cmo','CFO':'cfo','Entrenador':'coach'
};
export const staffRoles=Object.keys(staffRoleMap);
export const sponsorScopes=[
  {id:'local',name:'Local',detail:'Empresas de la ciudad y comarca. Alta probabilidad para clubes pequeños.'},
  {id:'regional',name:'Regional',detail:'Marcas de la comunidad o varias provincias. Mejor valor, más exigencia.'},
  {id:'national',name:'Nacional',detail:'Empresas con presencia española. Un club de 1RFEF puede no encontrar ninguna.'},
  {id:'global',name:'Multinacional',detail:'Marcas internacionales. Exigen alcance, categoría y reputación.'},
];
export const searchDurations=[{days:14,label:'2 semanas',mult:.72},{days:30,label:'1 mes',mult:1},{days:60,label:'2 meses',mult:1.45}];
export const kitStyles=['Lisa','Raya central','Rayas gruesas','Rayas finas','Banda diagonal','Franja horizontal'];
export const collarStyles=['Redondo','Pico','Polo'];
export const sleeveStyles=['Manga completa','Línea vertical','Borde de manga','Sin contraste'];
export const mediaTones=['Formal','Humor','Defensa del club','Cercano'];
export const eventCatalog={
  wedding:{name:'Boda / celebración privada',baseRevenue:14000,cost:4200,pitchDamage:1.2,fan:0,requires:'Sala hospitality',detail:'Ocupa una parte pequeña del recinto. Ingreso modesto y riesgo mínimo para el césped.'},
  corporate:{name:'Evento de empresa',baseRevenue:26000,cost:8000,pitchDamage:.5,fan:0,requires:'Hospitality',detail:'Salones, catering y visita al estadio. Buen negocio B2B sin tocar apenas el campo.'},
  concert:{name:'Concierto',baseRevenue:145000,cost:52000,pitchDamage:15,fan:1,requires:'Estadio',detail:'Gran ingreso potencial. Ocupa el estadio completo y puede dejar el césped muy tocado.'},
  community:{name:'Jornada de puertas abiertas',baseRevenue:4500,cost:7000,pitchDamage:2,fan:4,requires:'Estadio',detail:'No maximiza caja: fideliza familias, peñas y tejido local.'},
};

export const money=Base.money;
export const getActiveTactic=Base.getActiveTactic;
export const setTactic=Base.setTactic;
export const applyTacticalPreset=Base.applyTacticalPreset;
export const getFanTacticalSatisfaction=Base.getFanTacticalSatisfaction;
export const playerTacticalFit=Base.playerTacticalFit;
export const squadTacticalFit=Base.squadTacticalFit;
export const bestXI=Base.bestXI;
export const bestXIWithSlots=Base.bestXIWithSlots;
export const getCoachRequests=Base.getCoachRequests;
export const coachIntervene=Base.coachIntervene;
export const facilityBonuses=Base.facilityBonuses;
export const facilityScore=Base.facilityScore;
export const facilityUpkeep=Base.facilityUpkeep;
export const updateTicketZone=Base.updateTicketZone;
export const ticketProjection=Base.ticketProjection;
export const upgradeMerchChannel=Base.upgradeMerchChannel;
export const setMerchPrice=Base.setMerchPrice;
export const setBusinessPolicy=Base.setBusinessPolicy;
export const commercialUnitCatalog=Base.commercialUnitCatalog;
export const leaseCommercialUnit=Base.leaseCommercialUnit;

function isoForDay(day){const d=new Date(`${START_DATE}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+day);return d.toISOString().slice(0,10);}
export function formatGameDate(game){return new Intl.DateTimeFormat('es-ES',{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(`${game.calendarISO}T12:00:00Z`));}
function uid(prefix,game,extra=''){return `${prefix}-${game.day}-${hashString(`${extra}-${game.day}-${game.week}-${game.club.id}-${game.inbox?.length||0}`)%999999}`;}
function mail(game,{sender='Secretaría del club',subject,body,tone='info',screen=null,entityId=null}){
  const item={id:uid('mail',game,subject),day:game.day,date:game.calendarISO,sender,subject,body,tone,screen,entityId,unread:true};
  return {...game,inbox:[item,...(game.inbox||[])].slice(0,120)};
}
export function markMailRead(game,id){return {...game,inbox:game.inbox.map(m=>m.id===id?{...m,unread:false}:m)};}
export function unreadMail(game){return (game.inbox||[]).filter(x=>x.unread).length;}

function randomInitialLevel(club,group,id){
  if(id==='capacity'||id==='roof'||id==='standHeating')return 0;
  const r=rng(hashString(`${club.id}-${group}-${id}-initial-v43`))(),strength=clamp((club.prestige-42)/28,0,1);
  const chance=group==='stadium'?.48+strength*.18:group==='sport'?.34+strength*.16:.30+strength*.14;
  return r<chance?1:0;
}
function buildInitialLevels(club){
  const out={stadium:{},club:{},sport:{}};
  for(const group of Object.keys(out))for(const id of Object.keys(facilityDefs[group]))out[group][id]=randomInitialLevel(club,group,id);
  return out;
}
function cumulativeEffect(group,id,level,key){let v=0;for(let i=1;i<=level;i++)v+=Number(facilityDefs[group]?.[id]?.levels?.[i]?.effects?.[key]||0);return v;}
function kitPreferences(club){const palette=['#8b1e2d','#1f4f9a','#f2f2f2','#111827','#e8c547','#287a5b','#6b3fa0','#f07d2b'];const r=rng(hashString(`${club.id}-kit-pref`));return {primary:palette[Math.floor(r()*palette.length)],secondary:palette[Math.floor(r()*palette.length)],style:kitStyles[Math.floor(r()*kitStyles.length)],tradition:55+Math.floor(r()*36)};}
function ensureStats(p){return {...p,nationality:p.nationality||['España','Portugal','Argentina','Uruguay','Francia','Marruecos','Colombia'][hashString(p.name)%7],stats:p.stats||{apps:0,starts:0,minutes:0,goals:0,assists:0,yellow:0,ratingSum:0}};}

export function createGame(club,gm){
  let g=Base.createGame(club,gm);const levels=buildInitialLevels(club);const cs=levels.stadium.commercialSpaces||0;const commercialSlots=1+cumulativeEffect('stadium','commercialSpaces',cs,'commercialSlots');
  const prefs=kitPreferences(club);const kit={preferences:prefs,primary:prefs.primary,secondary:prefs.secondary==prefs.primary?'#ffffff':prefs.secondary,accent:'#ffffff',style:prefs.style,collar:'Redondo',sleeve:'Borde de manga',manufacturer:null,manufacturerOffers:[],manufacturerSearch:null,appeal:76,history:[]};
  g={...g,version:4,day:0,calendarISO:START_DATE,dateLabel:formatGameDate({calendarISO:START_DATE}),players:g.players.map(ensureStats),market:g.market.map(ensureStats),infrastructure:{...g.infrastructure,levels,projects:[],maxProjects:3},stadium:{...g.stadium,commercialSlots,condition:76},sponsorOffers:[],activeSponsorRights:[],sponsorSearches:{},sponsorNegotiations:{},staffPositions:['Entrenador'],staffSearches:{},staffCandidatePools:{},staffNegotiations:{},coachRecommendations:{},transferNegotiations:{},processes:[],kit,
    mediaProgram:{autographs:'important',channels:{instagram:true,x:true,tiktok:false,youtube:false},postsPerWeek:4,tone:'Cercano',programme:false,magazine:false,radio:false,tv:false},
    events:[],financeV4:{debt:0,debtRate:0,investments:[],investmentProfit:0,capitalContributions:0},boardV4:{requests:[],objectiveNegotiations:{}},trainingPlan:{intensity:'balanced',focus:'balanced',restDays:1},controlMode:'coach',matchReady:false};
  g=mail(g,{sender:'Presidenta de la directiva',subject:'Bienvenido: tus primeros objetivos',body:`La directiva espera que profesionalices ${club.name} sin comprometer la caja. Puedes negociar objetivos, pedir capital y decidir qué áreas construir primero.`,screen:'board'});
  g=mail(g,{sender:'Secretaría deportiva',subject:'El calendario ya está disponible',body:'Tienes resultados, clasificación, calendario y estadísticas dentro de Deportivo → Resultados y competición.',screen:'competitions'});
  g=mail(g,{sender:'Dirección comercial',subject:'Los derechos comerciales están vacíos',body:'No hay patrocinadores precargados. Decide qué derecho quieres activar, el nivel de empresa que buscas y cuánto tiempo estás dispuesto a esperar.',screen:'sponsors'});
  return g;
}

function currentPosition(game){return Math.max(1,game.table.findIndex(x=>x.id===game.club.id)+1);}
function annualRevenueEstimate(game){const played=Math.max(1,game.week-1);const seasonized=(game.finance.revenue/played)*38;return Math.max(game.club.cash*1.8,seasonized,900000);}
export function debtRatio(game){return (game.financeV4?.debt||0)/Math.max(1,annualRevenueEstimate(game));}

function processSponsorSearch(game,p){
  const {slotId,scope,duration}=p.payload;const slot=sponsorRights.find(x=>x.id===slotId);if(!slot)return game;
  const brand=game.brandScore||Base.getBrandScore(game);const scopeRank={local:0,regional:1,national:2,global:3}[scope];const r=rng(hashString(`${game.club.id}-${slotId}-${scope}-${duration}-${game.day}-search`));
  let chance=.92;if(scope==='regional')chance=clamp(.58+(brand-30)/100,.25,.9);if(scope==='national')chance=game.club.tier>=3?clamp((brand-38)/85,.04,.38):clamp((brand-25)/65,.2,.8);if(scope==='global')chance=game.club.tier>=3?0:clamp((brand-58)/55,.05,.68);
  chance*=duration===14?.72:duration===60?1.22:1;
  const found=r()<chance;let offers=[];
  if(found){const count=clamp(1+Math.floor(r()*(duration===60?4:duration===30?3:2)),1,4);const localA=['Talleres Rivera','Clínica Norte','Grupo del Puerto','Cerámicas Sol','Transportes Vega','Restaurante Plaza'];const regionalA=['Caja del Norte','Costa Telecom','Ruta Hotels','Ebro Energía','Motor Sierra','Mercados Levante'];const nationalA=['Nexo Bank','Brava Foods','Orbe Telecom','Aurea Logistics','Turia Mobility','Alma Retail'];const globalA=['NovaDrive','Helix Airways','Vertex Cloud','Atlas Global Bank','Apex Sportswear','Northstar Energy'];const pools={local:localA,regional:regionalA,national:nationalA,global:globalA};
    const base=(game.localFans*4.8+game.nationalFans*.9+game.globalFans*.18+brand*9500)*slot.mult*({local:.48,regional:.9,national:1.75,global:3.6}[scope]);
    offers=Array.from({length:count},(_,i)=>{const name=pools[scope][(Math.floor(r()*pools[scope].length)+i)%pools[scope].length];const annual=Math.max(4000,Math.round(base*(.72+r()*.45)/1000)*1000);return {id:`offer-${slotId}-${scope}-${game.day}-${i}`,slotId,brand:name,scope,sector:slot.sector||['Servicios','Finanzas','Alimentación','Tecnología'][Math.floor(r()*4)],annual,currentAnnual:annual,maxAnnual:Math.round(annual*(1.05+.05*scopeRank+r()*(.10+.03*scopeRank))),years:1+Math.floor(r()*4),bonusWin:Math.round(annual*(.01+r()*.03)/500)*500,activationAsk:Math.round(annual*(.03+r()*.05)/500)*500,patience:2+Math.floor(r()*3),fit:45+Math.floor(r()*51)};});
  }
  let next={...game,sponsorOffers:[...game.sponsorOffers.filter(x=>x.slotId!==slotId),...offers],sponsorSearches:{...game.sponsorSearches,[slotId]:{...game.sponsorSearches[slotId],status:'complete',results:offers.length}}};
  return mail(next,{sender:'Dirección comercial',subject:offers.length?`${offers.length} propuesta${offers.length>1?'s':''} para ${slot.short}`:`Búsqueda sin resultados: ${slot.short}`,body:offers.length?`La búsqueda ${scope} ha terminado. Hay ${offers.length} empresas interesadas. Puedes abrir conversaciones con cualquiera.`:`No hemos encontrado una empresa ${scope} dispuesta a comprar este derecho. Puedes repetir la búsqueda, ampliar el plazo o bajar el nivel objetivo.`,tone:offers.length?'positive':'warning',screen:'sponsors',entityId:slotId});
}
function processSponsorNegotiation(game,p){
  const {offerId,ask}=p.payload;const offer=game.sponsorOffers.find(x=>x.id===offerId);if(!offer)return game;const prev=game.sponsorNegotiations[offerId]||{round:0,tension:0,status:'idle'};const skill=game.gm.stats.finance;const r=rng(hashString(`${offerId}-${prev.round}-${ask}-${game.day}`));const max=offer.maxAnnual*(1+skill*.008);const stretch=(ask-offer.currentAnnual)/Math.max(1,offer.currentAnnual);const tension=clamp(prev.tension+Math.max(4,Math.round(stretch*60))-skill*.8,0,100);let status='counter',current=offer.currentAnnual,message='';
  if(ask<=max && stretch<=.04+skill*.012){status='accepted';current=Math.round(ask/500)*500;message=`Aceptan ${money(current)} al año.`;}
  else if((prev.round+1)>=offer.patience && (tension>58 || ask>max*1.08)){status='broken';message='La empresa da por terminadas las negociaciones.';}
  else {const improvement=(.012+skill*.004+r()*.018)*(1-Math.min(.7,tension/130));current=Math.min(max,Math.round(offer.currentAnnual*(1+improvement)/500)*500);message=`Suben su oferta a ${money(current)} anuales. La cuerda está en ${Math.round(tension)}%.`;}
  const sponsorOffers=game.sponsorOffers.map(x=>x.id===offerId?{...x,currentAnnual:current}:x);const neg={...prev,round:prev.round+1,tension:Math.round(tension),status,lastAsk:ask,message};let next={...game,sponsorOffers,sponsorNegotiations:{...game.sponsorNegotiations,[offerId]:neg}};
  return mail(next,{sender:offer.brand,subject:status==='accepted'?'Acuerdo económico alcanzado':status==='broken'?'Conversaciones terminadas':`Contraoferta de ${offer.brand}`,body:message,tone:status==='accepted'?'positive':status==='broken'?'negative':'info',screen:'sponsors',entityId:offerId});
}
function staffProfile(role,r){if(role==='Preparador físico')return ['Agresivo','Equilibrado','Saludable'][Math.floor(r()*3)];if(role==='Fisioterapeuta jefe'||role==='Médico jefe')return ['Prevención','Recuperación rápida','Carga conservadora'][Math.floor(r()*3)];if(role.includes('scouting'))return ['Datos','Red de contactos','Observación tradicional'][Math.floor(r()*3)];return ['Metódico','Innovador','Pragmático','Formador'][Math.floor(r()*4)];}
function entourageFor(game,coach){const r=rng(hashString(`${coach.id}-entourage-v4`));const roles=['Segundo entrenador','Preparador físico','Preparador de porteros','Fisioterapeuta jefe','Jefe de scouting nacional'];const n=2+Math.floor(r()*4);return roles.sort(()=>r()-.5).slice(0,n).map((role,i)=>{const c=generateStaff(game.club,role,1)[0];return {...c,id:`ent-${coach.id}-${i}`,role,profile:staffProfile(role,r),salary:Math.round(c.salary*(.8+r()*.35)/1000)*1000};});}
function processStaffSearch(game,p){const {role,duration}=p.payload;const count=duration===14?3:duration===30?5:8;const base=generateStaff(game.club,role,count);const r=rng(hashString(`${game.club.id}-${role}-${duration}-${game.day}`));const candidates=base.map(c=>({...c,profile:staffProfile(role,r),nationality:['España','Portugal','Argentina','Italia','Francia'][Math.floor(r()*5)],entourage:role==='Entrenador'?entourageFor(game,c):undefined}));let next={...game,staffCandidatePools:{...game.staffCandidatePools,[role]:candidates},staffSearches:{...game.staffSearches,[role]:{...game.staffSearches[role],status:'complete',results:candidates.length}}};return mail(next,{sender:'Recursos Humanos',subject:`Búsqueda completada: ${role}`,body:`Han llegado ${candidates.length} perfiles. El plazo de ${duration} días permitió ampliar la variedad de experiencia, coste y estilo.`,tone:'positive',screen:role==='Entrenador'?'coach':'staff',entityId:role});}
function processCoachStaffRecommendation(game,p){const {role}=p.payload;if(!game.staff.coach)return game;const r=rng(hashString(`${game.staff.coach.id}-${role}-recommend-${game.day}`));const base=generateStaff(game.club,role,1)[0];const candidate={...base,id:`coach-rec-${game.day}-${base.id}`,profile:staffProfile(role,r),nationality:['España','Portugal','Argentina','Italia','Francia'][Math.floor(r()*5)],recommendedByCoach:true,recommender:game.staff.coach.name,salary:Math.round(base.salary*(.98+r()*.12)/1000)*1000};const pool=[candidate,...(game.staffCandidatePools[role]||[]).filter(x=>!x.recommendedByCoach)];let next={...game,staffCandidatePools:{...game.staffCandidatePools,[role]:pool},coachRecommendations:{...(game.coachRecommendations||{}),[role]:candidate.id}};return mail(next,{sender:game.staff.coach.name,subject:`Mi recomendación para ${role}`,body:`Te recomiendo a ${candidate.name} (${candidate.rating}/100, perfil ${candidate.profile}). Es alguien con quien me gustaría trabajar. Puedes negociar con él o seguir tu propia búsqueda, pero entenderé la decisión como una señal sobre mi autonomía.`,tone:'info',screen:'staff',entityId:role});}
function processStaffNegotiation(game,p){const {role,candidateId,salary,acceptedEntourage=[]}=p.payload;const c=(game.staffCandidatePools[role]||[]).find(x=>x.id===candidateId);if(!c)return game;const key=`${role}:${candidateId}`;const prev=game.staffNegotiations[key]||{round:0,tension:0,status:'idle'};const skill=role==='Entrenador'?game.gm.stats.players:game.gm.stats.finance;const entourageDiscount=role==='Entrenador'?acceptedEntourage.length*.025:0;const target=c.salary*(1-entourageDiscount-skill*.005);const score=salary/Math.max(1,target);const tension=clamp(prev.tension+Math.max(3,Math.round((1-score)*65))-skill*.5,0,100);let status='counter',counter=salary,message='';
  if(score>=.97){status='accepted';counter=salary;message=`${c.name} acepta ${money(salary)}/año.`;}
  else if((prev.round+1)>=Math.max(2,c.flexibility?Math.round(c.flexibility/25):3)&&tension>60){status='broken';message=`${c.name} retira su candidatura.`;}
  else {counter=Math.round(target*(.99-.012*(prev.round+1))/1000)*1000;message=`Contraoferta: ${money(counter)}/año.`;}
  const neg={...prev,round:prev.round+1,tension:Math.round(tension),status,counter,lastSalary:salary,acceptedEntourage,message};let next={...game,staffNegotiations:{...game.staffNegotiations,[key]:neg}};return mail(next,{sender:c.name,subject:status==='accepted'?`Acuerdo con ${c.name}`:status==='broken'?`${c.name} se retira`:`Contraoferta de ${c.name}`,body:message,tone:status==='accepted'?'positive':status==='broken'?'negative':'info',screen:role==='Entrenador'?'coach':'staff',entityId:key});}
function processTransferNegotiation(game,p){
  const {playerId,stage,amount,salary,signing}=p.payload;const player=game.market.find(x=>x.id===playerId);if(!player)return game;const prev=game.transferNegotiations[playerId]||{stage:'club',round:0,tension:0,status:'idle'};let result,nextState;
  if(stage==='club'){result=Base.evaluateClubOffer(game,player,amount,prev.round+1);nextState={...prev,stage:result.status==='accepted'?'player':'club',round:prev.round+1,status:result.status,counter:result.counter,lastAmount:amount,message:result.message};}
  else {result=Base.evaluatePlayerOffer(game,player,salary,signing,prev.round+1);nextState={...prev,stage:result.status==='accepted'?'ready':'player',round:prev.round+1,status:result.status,counterSalary:result.salary,counterSigning:result.signing,lastSalary:salary,lastSigning:signing,message:result.message};}
  let next={...game,transferNegotiations:{...game.transferNegotiations,[playerId]:nextState}};return mail(next,{sender:stage==='club'?player.club:`Agente de ${player.name}`,subject:result.status==='accepted'?(stage==='club'?'El club acepta negociar contrato':'Acuerdo con el jugador'):result.status==='walked'?'Negociación rota':`Respuesta por ${player.name}`,body:result.message,tone:result.status==='accepted'?'positive':result.status==='walked'?'negative':'info',screen:'transfers',entityId:playerId});
}
function processManufacturerSearch(game,p){const {duration}=p.payload;const r=rng(hashString(`${game.club.id}-manufacturer-${duration}-${game.day}`));const brand=game.brandScore;const pools=brand<45?['IberSport','Roca Teamwear','Norte Kit','Línea Once']:brand<65?['IberSport','KappaNova','Atria Sport','Marea Teamwear','Orion Kit']:['Apex Sportswear','Orion Global','Vega Performance','Atria Sport'];const count=duration===14?3:duration===30?4:5;const offers=Array.from({length:count},(_,i)=>{const quality=48+Math.floor(r()*(brand<45?22:brand<65?32:42));return {id:`kit-${game.day}-${i}`,name:pools[i%pools.length],materialQuality:quality,performanceBoost:quality>=84?2:quality>=70?1:0,clubShare:clamp(Math.round(58+r()*28-(quality-65)*.12),50,90),colorControl:r()>(quality>78?.45:.18),styleControl:r()>(quality>78?.5:.22),minimumOrder:100+Math.floor(r()*12)*100,years:2+Math.floor(r()*4),guarantee:Math.round((game.localFans*3+brand*4000)*(0.5+r()*.8)/5000)*5000};});let next={...game,kit:{...game.kit,manufacturerSearch:{status:'complete',duration,results:offers.length},manufacturerOffers:offers}};return mail(next,{sender:'Dirección comercial',subject:'Propuestas de fabricantes de equipación',body:`Han llegado ${offers.length} propuestas. Compara calidad, impacto deportivo, margen de ventas, control creativo y pedido mínimo.`,tone:'positive',screen:'kit'});}
function processBoardRequest(game,p){const {kind,amount,objectiveId}=p.payload;const r=rng(hashString(`${game.club.id}-${kind}-${amount}-${game.day}`));let next=game;if(kind==='capital'){
  const ratio=debtRatio(game);const score=game.boardConfidence*.45+game.gm.stats.board*3-ratio*35+(r()*18-9);const accepted=score>48;const granted=accepted?Math.round(amount*(score>70?1:.65)/10000)*10000:0;next={...game,cash:game.cash+granted,financeV4:{...game.financeV4,capitalContributions:game.financeV4.capitalContributions+granted},boardConfidence:clamp(game.boardConfidence+(accepted?-1:-4),5,99)};return mail(next,{sender:'Consejo de administración',subject:accepted?'Aportación de capital aprobada':'Aportación de capital rechazada',body:accepted?`El consejo aprueba ${money(granted)}. Espera que el capital se utilice para el plan indicado y no para tapar pérdidas recurrentes.`:'El consejo considera que la caja, la deuda o la justificación no permiten una aportación adicional ahora mismo.',tone:accepted?'positive':'negative',screen:'board'});
  }
  const obj=game.objectives.find(x=>x.id===objectiveId);if(!obj)return game;const accepted=r()*100<clamp(35+game.gm.stats.board*3+game.boardConfidence*.25,20,88);const objectives=game.objectives.map(x=>x.id===objectiveId&&accepted?{...x,target:Math.min(14,(x.target||10)+2),label:x.id==='league'?`Terminar Top ${Math.min(14,(x.target||10)+2)}`:x.label}:x);next={...game,objectives,boardConfidence:clamp(game.boardConfidence+(accepted?-1:-2),5,99)};return mail(next,{sender:'Consejo de administración',subject:accepted?'Objetivo renegociado':'Objetivo mantenido',body:accepted?`Aceptan rebajar temporalmente la exigencia de “${obj.label}”. La concesión reduce algo tu crédito político.`:`No aceptan modificar “${obj.label}”. Consideran que el plan original sigue siendo razonable.`,tone:accepted?'info':'warning',screen:'board'});
}
function processInvestment(game,p){const inv=game.financeV4.investments.find(x=>x.id===p.payload.investmentId);if(!inv||inv.status!=='active')return game;const r=rng(hashString(`${inv.id}-return`));const annual=inv.type==='low'?.05:(-.05+r()*.25);const days=inv.termDays;const rate=inv.type==='low'?annual*(days/365):annual*Math.min(1,days/365+.25);const result=Math.round(inv.amount*(1+rate));const profit=result-inv.amount;const investments=game.financeV4.investments.map(x=>x.id===inv.id?{...x,status:'matured',returnRate:rate,result}:x);let next={...game,cash:game.cash+result,financeV4:{...game.financeV4,investments,investmentProfit:game.financeV4.investmentProfit+profit},boardConfidence:clamp(game.boardConfidence+(profit>=0?1:-3),5,99)};return mail(next,{sender:'Tesorería',subject:`Inversión ${profit>=0?'cerrada con beneficio':'cerrada con pérdida'}`,body:`Capital recuperado: ${money(result)}. Resultado: ${profit>=0?'+':''}${money(profit)} (${(rate*100).toFixed(1)}%).`,tone:profit>=0?'positive':'negative',screen:'finance'});}
function completeFacility(game,p){const {group,assetId,targetLevel,startLevel}=p.payload;const def=facilityDefs[group]?.[assetId];if(!def)return game;let stadium={...game.stadium};for(let i=startLevel+1;i<=targetLevel;i++){const e=def.levels[i]?.effects||{};if(e.capacity)stadium.capacity+=e.capacity;if(e.vipSeats)stadium.vipSeats+=e.vipSeats;if(e.commercialSlots)stadium.commercialSlots+=e.commercialSlots;}
  const levels={...game.infrastructure.levels,[group]:{...game.infrastructure.levels[group],[assetId]:targetLevel}};let next={...game,stadium,infrastructure:{...game.infrastructure,levels}};return mail(next,{sender:'Director de operaciones',subject:`Obra terminada: ${def.levels[targetLevel].name}`,body:`El proyecto de ${def.name} ha finalizado. La instalación ya opera en el nivel ${targetLevel}.`,tone:'positive',screen:group==='stadium'?'stadium':group==='club'?'clubFacilities':'sportFacilities',entityId:assetId});}
function processEvent(game,event){const d=eventCatalog[event.type];const r=rng(hashString(`${event.id}-event`));const revenue=Math.round(d.baseRevenue*(.78+r()*.5)*(1+game.brandScore/180));const remainingCost=Math.max(0,d.cost-(event.deposit||0));const net=revenue-remainingCost;const condition=clamp(game.stadium.condition-d.pitchDamage,20,100);let next={...game,cash:game.cash+net,stadium:{...game.stadium,condition},fanSentiment:clamp(game.fanSentiment+d.fan,0,100),events:game.events.map(e=>e.id===event.id?{...e,status:'completed',revenue,net}:e),finance:{...game.finance,revenue:game.finance.revenue+revenue,costs:game.finance.costs+remainingCost,events:game.finance.events+revenue}};return mail(next,{sender:'Eventos del estadio',subject:`Evento completado: ${d.name}`,body:`Ingresos ${money(revenue)}, costes totales ${money(d.cost)} (incluida la señal ya pagada), neto final ${money(revenue-d.cost)}. Estado del césped: ${Math.round(condition)}/100.`,tone:(revenue-d.cost)>=0?'positive':'warning',screen:'hospitality'});}
function processMerchProduction(game,p){const {key,qty}=p.payload;const product={shirt:'camisetas',scarf:'bufandas',cap:'gorras'}[key]||'productos';const inv={...game.merch.inventory,[key]:(game.merch.inventory[key]||0)+qty};let next={...game,merch:{...game.merch,inventory:inv}};return mail(next,{sender:'Producción y logística',subject:`Fabricación terminada: ${qty} ${product}`,body:`El lote ya ha llegado al almacén y está disponible para venta. Stock actual: ${inv[key]} unidades.`,tone:'positive',screen:'merch'});}
function processDue(game){const due=(game.processes||[]).filter(p=>p.dueDay<=game.day),pending=(game.processes||[]).filter(p=>p.dueDay>game.day);let next={...game,processes:pending};for(const p of due){if(p.type==='sponsorSearch')next=processSponsorSearch(next,p);if(p.type==='sponsorNegotiation')next=processSponsorNegotiation(next,p);if(p.type==='staffSearch')next=processStaffSearch(next,p);if(p.type==='coachStaffRecommendation')next=processCoachStaffRecommendation(next,p);if(p.type==='staffNegotiation')next=processStaffNegotiation(next,p);if(p.type==='transferNegotiation')next=processTransferNegotiation(next,p);if(p.type==='manufacturerSearch')next=processManufacturerSearch(next,p);if(p.type==='boardRequest')next=processBoardRequest(next,p);if(p.type==='investment')next=processInvestment(next,p);if(p.type==='facility')next=completeFacility(next,p);if(p.type==='merchProduction')next=processMerchProduction(next,p);}return next;}

function allocateMatchStats(before,after){if((after.history?.length||0)<=(before.history?.length||0))return after;const match=after.lastMatch;if(!match)return after;const assignments=Base.bestXIWithSlots(before),xi=assignments.map(x=>x.player).filter(Boolean),r=rng(hashString(`${after.club.id}-${match.round}-playerstats-v43`));let goalPool=match.goalsFor,assistPool=Math.max(0,match.goalsFor-1);const scorerWeights=xi.map(p=>['DC','ED','EI','MP'].includes(p.pos)?5:['MC','MCD'].includes(p.pos)?2:1),scorerIds=[];while(goalPool-->0&&xi.length){let total=scorerWeights.reduce((a,b)=>a+b,0),x=r()*total,idx=0;for(;idx<scorerWeights.length;idx++){x-=scorerWeights[idx];if(x<=0)break;}scorerIds.push(xi[Math.min(idx,xi.length-1)]?.id);}const assistIds=[];while(assistPool-->0&&xi.length)assistIds.push(xi[Math.floor(r()*xi.length)]?.id);
  const ratings={};for(const a of assignments){const p=a.player;if(!p)continue;const goals=scorerIds.filter(x=>x===p.id).length,assists=assistIds.filter(x=>x===p.id).length;let rating=6.15+(match.goalsFor-match.goalsAgainst)*.18+goals*.72+assists*.28+(r()*.9-.42)-(a.outOfPosition?.32:0);if(p.pos==='POR'&&match.goalsAgainst===0)rating+=.45;ratings[p.id]=clamp(Math.round(rating*10)/10,3.5,9.8);}
  const players=after.players.map(p=>{let st={...(p.stats||{apps:0,starts:0,minutes:0,goals:0,assists:0,yellow:0,ratingSum:0})};const starter=xi.some(x=>x.id===p.id);if(starter){st.apps++;st.starts++;st.minutes+=90;st.goals+=scorerIds.filter(x=>x===p.id).length;st.assists+=assistIds.filter(x=>x===p.id).length;if(r()<.13)st.yellow++;st.ratingSum+=ratings[p.id]||6;}return {...p,stats:st};});
  const scorers=scorerIds.map(id=>players.find(p=>p.id===id)?.name).filter(Boolean);const avg=xi.length?xi.reduce((a,p)=>a+(ratings[p.id]||6),0)/xi.length:6;const stars=clamp(Math.round(((avg-4)/1.05)*2)/2,1,5);const report={lineup:assignments.filter(a=>a.player).map(a=>({slot:a.slot,id:a.player.id,name:a.player.name,pos:a.player.pos,outOfPosition:a.outOfPosition,rating:ratings[a.player.id]})),scorers,teamStars:stars};
  const history=(after.history||[]).map((h,i)=>i===after.history.length-1?{...h,report}:h);return {...after,players,matchReport:report,history};}
function applyWeeklyV4(game){
  let next=game;const m=game.mediaProgram;const channels=Object.values(m.channels).filter(Boolean).length;const productReach=(m.programme?14:0)+(m.magazine?32:0)+(m.radio?180:0)+(m.tv?850:0);const reachGain=Math.round((game.localFans*.0012+channels*18+m.postsPerWeek*7+productReach)*(1+(Base.facilityBonuses(game).media||0)/35));const mediaCost=(channels*90+m.postsPerWeek*35+(m.programme?650:0)+(m.magazine?900:0)+(m.radio?2200:0)+(m.tv?12000:0));const loyalty=(m.autographs==='always'?1:m.autographs==='sometimes'?.5:m.autographs==='important'?.25:0)+(m.programme?.35:0)+(m.magazine?.35:0),autographLoad=m.autographs==='always'?.65:m.autographs==='sometimes'?.25:0;next={...next,business:{...next.business,media:{...next.business.media,digitalReach:next.business.media.digitalReach+reachGain}},cash:next.cash-mediaCost,fanSentiment:clamp(next.fanSentiment+loyalty,0,100),finance:{...next.finance,costs:next.finance.costs+mediaCost,media:next.finance.media}};
  const tp=next.trainingPlan||{intensity:'balanced',focus:'balanced',restDays:1};let players=next.players.map(p=>{let fitness=p.fitness,sharpness=clamp(p.sharpness-autographLoad,40,99),overall=p.overall;if(tp.focus==='fitness')fitness=clamp(fitness+2,40,99);if(tp.focus==='recovery')fitness=clamp(fitness+4,40,99);if(tp.focus==='tactical')sharpness=clamp(sharpness+2,40,99);if(tp.focus==='youth'&&p.age<=21&&p.overall<p.potential&&hashString(`${p.id}-${next.week}-youth`)%100<8)overall++;return {...p,fitness,sharpness,overall};});next={...next,players};
  const ratio=debtRatio(next);let board=next.boardConfidence;if(ratio>.5)board-=2;else if(ratio<.2&&next.cash>0)board+=.5;if(next.financeV4.investmentProfit<0)board-=.5;next={...next,boardConfidence:clamp(board,5,99)};return next;
}
function recoverPitch(game){const pitchLevel=game.infrastructure.levels.stadium.pitch||0;const recovery=.08+pitchLevel*.07;return {...game,stadium:{...game.stadium,condition:clamp(game.stadium.condition+recovery,20,100)}};}

export function nextMatchDay(game){return game.week<=38?5+(game.week-1)*7:null;}
export function daysToNextMatch(game){const d=nextMatchDay(game);return d==null?null:Math.max(0,d-game.day);}
export function isMatchReady(game){const d=nextMatchDay(game);return d!=null&&game.day>=d;}
function settleScheduledMatch(input){let before={...input,matchReady:false},game=Base.advanceWeek(before);if(before.staff.coach&&!game.staff.coach){game={...game,controlMode:'vacant'};game=mail(game,{sender:'Presidencia',subject:'El entrenador ha presentado su dimisión',body:'La relación se ha roto y el banquillo queda vacante. Debes asumir temporalmente, nombrar un interino o iniciar una búsqueda.',tone:'negative',screen:'coach'});}game=allocateMatchStats(before,game);game=applyWeeklyV4(game);if(game.lastMatch)game=mail(game,{sender:'Secretaría deportiva',subject:`Resultado: ${game.club.name} ${game.lastMatch.goalsFor}-${game.lastMatch.goalsAgainst} ${game.lastMatch.opponent}`,body:`Asistencia ${game.lastMatch.attendance.toLocaleString('es-ES')}. Posición actual: ${game.lastMatch.position}º. Consulta el informe completo del partido.`,tone:game.lastMatch.goalsFor>game.lastMatch.goalsAgainst?'positive':game.lastMatch.goalsFor<game.lastMatch.goalsAgainst?'negative':'info',screen:'matchday'});return {...game,matchReady:false,dateLabel:formatGameDate(game),brandScore:Base.getBrandScore(game)};}
export function getMatchPreview(game){const m=game.schedule[game.week-1];if(!m)return null;const ticket=Base.ticketProjection(game),previous=[...(game.history||[])].reverse().find(h=>h.opponent===m.opponent);const r=rng(hashString(`${game.club.id}-${m.opponentId}-${game.week}-preview-v43`));const seasonPassHolders=ticket.zones.reduce((s,z)=>s+z.seasonSold,0),seasonAttendance=Math.min(seasonPassHolders,Math.round(seasonPassHolders*(.88+r()*.10))),regularSold=Math.max(0,ticket.attendance-seasonPassHolders);const homeStrength=game.players.reduce((s,p)=>s+p.overall,0)/Math.max(1,game.players.length),opp=primeraFederacionClubs.find(c=>c.id===m.opponentId),diff=(homeStrength-(opp?.sporting||55))/14+(m.home?.18:-.12),homePct=clamp(Math.round(34+diff*14),12,72),drawPct=clamp(Math.round(31-Math.abs(diff)*4),18,38),awayPct=100-homePct-drawPct;const televised=game.club.tier<3||game.brandScore>=62||(hashString(`${game.week}-${game.club.id}-tv`)%100<18);return {match:m,previous,seasonPassHolders,seasonAttendance,regularCapacity:Math.max(0,game.stadium.capacity-seasonPassHolders),regularSold,ticketRevenue:ticket.revenue,televised,audience:televised?Math.round((18000+game.localFans*2.4+game.nationalFans*.65)*(1+game.brandScore/100)):0,odds:{home:homePct,draw:drawPct,away:awayPct}};}
export function simulateCurrentMatch(game){if(!isMatchReady(game))return {game,timeline:[],report:null};const settled=settleScheduledMatch(game),m=settled.lastMatch,r=rng(hashString(`${game.club.id}-${game.week}-timeline-v43`)),finalFor=m.goalsFor,finalAgainst=m.goalsAgainst;let hf=0,ha=0,shotsF=0,shotsA=0,onF=0,onA=0,cornersF=0,cornersA=0,cardsF=0,cardsA=0,foulsF=0,foulsA=0;const goalMinutesF=Array.from({length:finalFor},()=>1+Math.floor(r()*89)).sort((a,b)=>a-b),goalMinutesA=Array.from({length:finalAgainst},()=>1+Math.floor(r()*89)).sort((a,b)=>a-b);const timeline=[];for(const minute of [15,30,45,60,75,90]){hf=goalMinutesF.filter(x=>x<=minute).length;ha=goalMinutesA.filter(x=>x<=minute).length;shotsF+=Math.floor(r()*4)+1;shotsA+=Math.floor(r()*4)+1;onF=Math.max(hf,Math.min(shotsF,onF+Math.floor(r()*3)));onA=Math.max(ha,Math.min(shotsA,onA+Math.floor(r()*3)));cornersF+=Math.floor(r()*3);cornersA+=Math.floor(r()*3);cardsF+=r()<.38?1:0;cardsA+=r()<.38?1:0;foulsF+=2+Math.floor(r()*4);foulsA+=2+Math.floor(r()*4);const possession=clamp(Math.round(49+(r()-.5)*14+(m.goalsFor-m.goalsAgainst)*1.5),35,65);timeline.push({minute,score:[hf,ha],shots:[shotsF,shotsA],onTarget:[onF,onA],corners:[cornersF,cornersA],cards:[cardsF,cardsA],fouls:[foulsF,foulsA],possession:[possession,100-possession]});}return {game:settled,timeline,report:settled.matchReport};}
export function advanceDays(input,count){let game=input;if(isMatchReady(game))return {...game,matchReady:true};for(let i=0;i<count;i++){
  const due=nextMatchDay(game);if(due!=null&&game.day>=due){game={...game,matchReady:true};break;}game={...game,day:game.day+1,calendarISO:isoForDay(game.day+1)};game=recoverPitch(game);game=processDue(game);for(const ev of game.events.filter(e=>e.status==='scheduled'&&e.day===game.day))game=processEvent(game,ev);if(due!=null&&game.day>=due){game={...game,matchReady:true,dateLabel:formatGameDate(game),brandScore:Base.getBrandScore(game)};break;}game={...game,dateLabel:formatGameDate(game),brandScore:Base.getBrandScore(game)};
 }return game;}
export const advanceDay=(g)=>advanceDays(g,1);export const advanceMonth=(g)=>advanceDays(g,30);export function advanceToNextMatch(game){const d=daysToNextMatch(game);return d==null?game:advanceDays(game,Math.max(0,d));}

export function activateSponsorRight(game,slotId){if((game.activeSponsorRights||[]).includes(slotId))return game;const right=sponsorRights.find(x=>x.id===slotId);if(!right)return game;return {...game,activeSponsorRights:[...(game.activeSponsorRights||[]),slotId]};}
export function startSponsorSearch(game,slotId,scope,duration){if(game.sponsors.some(s=>s.slotId===slotId))return game;if((game.processes||[]).some(p=>p.type==='sponsorSearch'&&p.payload.slotId===slotId))return game;const process={id:uid('search-sponsor',game,slotId),type:'sponsorSearch',dueDay:game.day+duration,payload:{slotId,scope,duration}};return {...game,processes:[...game.processes,process],sponsorSearches:{...game.sponsorSearches,[slotId]:{status:'searching',scope,duration,dueDay:process.dueDay}},sponsorOffers:game.sponsorOffers.filter(x=>x.slotId!==slotId)};}
export function submitSponsorNegotiation(game,offerId,ask){const offer=game.sponsorOffers.find(x=>x.id===offerId);if(!offer||game.sponsorNegotiations[offerId]?.status==='waiting')return game;const process={id:uid('neg-sponsor',game,offerId),type:'sponsorNegotiation',dueDay:game.day+1,payload:{offerId,ask:Number(ask)}};return {...game,processes:[...game.processes,process],sponsorNegotiations:{...game.sponsorNegotiations,[offerId]:{...(game.sponsorNegotiations[offerId]||{round:0,tension:0}),status:'waiting',lastAsk:Number(ask),message:'Propuesta enviada. Responderán mañana.'}}};}
export function signSponsor(game,offerId){const offer=game.sponsorOffers.find(x=>x.id===offerId),neg=game.sponsorNegotiations[offerId];if(!offer||neg?.status!=='accepted')return game;const deal={...offer,annual:offer.currentAnnual,remainingYears:offer.years};let next={...game,sponsors:[...game.sponsors.filter(x=>x.slotId!==offer.slotId),deal],sponsorOffers:game.sponsorOffers.filter(x=>x.slotId!==offer.slotId)};return mail(next,{sender:'Dirección comercial',subject:`Contrato firmado con ${offer.brand}`,body:`${money(deal.annual)}/año durante ${deal.years} años para ${sponsorRights.find(x=>x.id===offer.slotId)?.name}.`,tone:'positive',screen:'sponsors'});}

export function createStaffPosition(game,role){if(game.staffPositions.includes(role))return game;return {...game,staffPositions:[...game.staffPositions,role]};}
export function startStaffSearch(game,role,duration){if((game.processes||[]).some(p=>['staffSearch','coachStaffRecommendation'].includes(p.type)&&p.payload.role===role))return game;const process={id:uid('search-staff',game,role),type:'staffSearch',dueDay:game.day+duration,payload:{role,duration}};return {...game,processes:[...game.processes,process],staffSearches:{...game.staffSearches,[role]:{status:'searching',duration,dueDay:process.dueDay}},staffCandidatePools:{...game.staffCandidatePools,[role]:[]}};}
export function askCoachStaffRecommendation(game,role){if(!game.staff.coach||game.staff.coach.interim)return game;if((game.processes||[]).some(p=>['staffSearch','coachStaffRecommendation'].includes(p.type)&&p.payload.role===role))return game;const process={id:uid('coach-rec',game,role),type:'coachStaffRecommendation',dueDay:game.day+1,payload:{role}};return {...game,processes:[...game.processes,process]};}
export function submitStaffNegotiation(game,role,candidateId,salary,acceptedEntourage=[]){const key=`${role}:${candidateId}`;if(game.staffNegotiations[key]?.status==='waiting')return game;const process={id:uid('neg-staff',game,key),type:'staffNegotiation',dueDay:game.day+1,payload:{role,candidateId,salary:Number(salary),acceptedEntourage}};return {...game,processes:[...game.processes,process],staffNegotiations:{...game.staffNegotiations,[key]:{...(game.staffNegotiations[key]||{round:0,tension:0}),status:'waiting',lastSalary:Number(salary),acceptedEntourage,message:'Oferta enviada. Respuesta mañana.'}}};}
function staffKey(role){return staffRoleMap[role]||role;}
export function signStaffAgreement(game,role,candidateId){const key=`${role}:${candidateId}`,neg=game.staffNegotiations[key],c=(game.staffCandidatePools[role]||[]).find(x=>x.id===candidateId);if(!c||neg?.status!=='accepted')return game;const k=staffKey(role);if(game.staff[k])return game;const signed={...c,salary:neg.lastSalary,role};let staff={...game.staff,[k]:signed},positions=game.staffPositions.includes(role)?game.staffPositions:[...game.staffPositions,role],cost=Math.round(neg.lastSalary*.1);if(game.cash<cost)return game;
  if(role==='Entrenador'){for(const ent of (c.entourage||[]).filter(x=>neg.acceptedEntourage.includes(x.id))){const ek=staffKey(ent.role);if(!staff[ek]){staff[ek]=ent;if(!positions.includes(ent.role))positions.push(ent.role);}}}
  let relationship=role==='Entrenador'?{trust:70,respect:58,interventions:0,autonomy:'consultation'}:{...game.coachRelationship};if(role!=='Entrenador'&&game.staff.coach){const recId=game.coachRecommendations?.[role];if(recId)relationship.trust=clamp((relationship.trust||60)+(recId===c.id?4:-4),0,100);}let next={...game,cash:game.cash-cost,staff,staffPositions:positions,controlMode:role==='Entrenador'?'coach':game.controlMode,coachRelationship:relationship,finance:{...game.finance,costs:game.finance.costs+cost}};return mail(next,{sender:'Recursos Humanos',subject:`Incorporación: ${c.name}`,body:`${c.name} se incorpora como ${role} por ${money(neg.lastSalary)}/año.${c.recommendedByCoach?' El entrenador valora que hayas respaldado su recomendación.':game.coachRecommendations?.[role]?' Has elegido otro perfil distinto al recomendado por el entrenador.':''}`,tone:'positive',screen:role==='Entrenador'?'coach':'staff'});}
export function dismissStaff(game,role){const k=staffKey(role),person=game.staff[k];if(!person)return game;const severance=Math.round(person.salary*.16);if(game.cash<severance)return game;let staff={...game.staff,[k]:null};let next={...game,cash:game.cash-severance,staff,finance:{...game.finance,costs:game.finance.costs+severance}};if(game.staff.coach&&role!=='Entrenador'&&game.staff.coach.entourage?.some(e=>e.role===role))next={...next,coachRelationship:{...next.coachRelationship,trust:clamp(next.coachRelationship.trust-7,0,100)}};return mail(next,{sender:'Recursos Humanos',subject:`Salida de ${person.name}`,body:`Has extinguido el puesto ocupado por ${person.name}. Indemnización: ${money(severance)}.`,tone:'warning',screen:'staff'});}

export function fireCoach(game){const coach=game.staff.coach;if(!coach)return game;const pos=currentPosition(game),good=pos<=6,bad=pos>=13;const severance=Math.round(coach.salary*(.22+.09*(coach.contractYears||1)));if(game.cash<severance)return game;const boardDelta=good?-8:bad?3:-2,fanDelta=good?-7:bad?5:-1;let next={...game,cash:game.cash-severance,staff:{...game.staff,coach:null},controlMode:'vacant',boardConfidence:clamp(game.boardConfidence+boardDelta,0,100),fanSentiment:clamp(game.fanSentiment+fanDelta,0,100),coachRelationship:{trust:0,respect:0,interventions:0,autonomy:'vacant'},finance:{...game.finance,costs:game.finance.costs+severance}};return mail(next,{sender:'Presidencia',subject:`Destitución de ${coach.name}`,body:`La salida cuesta ${money(severance)}. Reacción directiva ${boardDelta>=0?'+':''}${boardDelta}; afición ${fanDelta>=0?'+':''}${fanDelta}. Ahora debes nombrar interino, asumir tú o buscar entrenador.`,tone:good?'negative':bad?'positive':'warning',screen:'coach'});}
export function takeControl(game){if(game.staff.coach)return game;return {...game,controlMode:'self'};}
export function appointInterim(game,key){if(game.staff.coach)return game;const person=game.staff[key];if(!person)return game;const coach={...person,id:`interim-${person.id}`,role:'Entrenador interino',salary:0,tactic:person.tactic||game.gmTactic,rating:Math.round((person.rating||55)*.88),interim:true,interimSource:key,ego:30,flexibility:80,reputation:Math.round((person.reputation||50)*.75)};return {...game,staff:{...game.staff,coach},controlMode:'coach',coachRelationship:{trust:78,respect:50,interventions:0,autonomy:'interim'}};}

export function submitClubOffer(game,playerId,amount){const n=game.transferNegotiations[playerId];if(n?.status==='waiting')return game;const process={id:uid('transfer-club',game,playerId),type:'transferNegotiation',dueDay:game.day+1,payload:{playerId,stage:'club',amount:Number(amount)}};return {...game,processes:[...game.processes,process],transferNegotiations:{...game.transferNegotiations,[playerId]:{...(n||{stage:'club',round:0,tension:0}),status:'waiting',lastAmount:Number(amount),message:'Oferta enviada al club. Responderán mañana.'}}};}
export function submitPlayerOffer(game,playerId,salary,signing){const n=game.transferNegotiations[playerId];if(n?.status==='waiting')return game;const process={id:uid('transfer-player',game,playerId),type:'transferNegotiation',dueDay:game.day+1,payload:{playerId,stage:'player',salary:Number(salary),signing:Number(signing)}};return {...game,processes:[...game.processes,process],transferNegotiations:{...game.transferNegotiations,[playerId]:{...(n||{stage:'player',round:0}),stage:'player',status:'waiting',lastSalary:Number(salary),lastSigning:Number(signing),message:'Oferta contractual enviada. Respuesta mañana.'}}};}
export function completeTransfer(game,playerId){const n=game.transferNegotiations[playerId],p=game.market.find(x=>x.id===playerId);if(!p||n?.stage!=='ready'||n.status!=='accepted')return game;const fee=p.club==='Libre'?0:(n.lastAmount||p.seller.asking);return Base.completeTransfer(game,p,fee,n.lastSalary,n.lastSigning);}

export function startManufacturerSearch(game,duration){if((game.processes||[]).some(p=>p.type==='manufacturerSearch'))return game;const process={id:uid('manufacturer',game),type:'manufacturerSearch',dueDay:game.day+duration,payload:{duration}};return {...game,processes:[...game.processes,process],kit:{...game.kit,manufacturerSearch:{status:'searching',duration,dueDay:process.dueDay},manufacturerOffers:[]}};}
export function signManufacturer(game,id){const m=game.kit.manufacturerOffers.find(x=>x.id===id);if(!m)return game;return {...game,kit:{...game.kit,manufacturer:m,manufacturerOffers:[]}};}
function colorMatch(a,b){return a.toLowerCase()===b.toLowerCase()?100:45;}
export function saveKitDesign(game,patch){const manufacturer=game.kit.manufacturer;if(manufacturer&&!manufacturer.colorControl&&(patch.primary||patch.secondary))patch={...patch,primary:game.kit.primary,secondary:game.kit.secondary};if(manufacturer&&!manufacturer.styleControl&&(patch.style||patch.sleeve||patch.collar))patch={...patch,style:game.kit.style,sleeve:game.kit.sleeve,collar:game.kit.collar};const nextKit={...game.kit,...patch};const p=nextKit.preferences;const tradition=(colorMatch(nextKit.primary,p.primary)*.5+colorMatch(nextKit.secondary,p.secondary)*.18+(nextKit.style===p.style?100:55)*.22+p.tradition*.1);const novelty=game.kit.history.length===0?4:nextKit.style!==game.kit.style?7:0;nextKit.appeal=clamp(Math.round(tradition*.78+22+novelty),35,98);return {...game,kit:nextKit};}

export function produceMerch(game,key,qty){qty=Math.floor(Number(qty));const base={shirt:17,scarf:6,cap:8}[key];if(!base||qty<=0)return game;const b=Base.facilityBonuses(game),pending=(game.processes||[]).filter(p=>p.type==='merchProduction').reduce((s,p)=>s+(p.payload.qty||0),0),inventory=Object.values(game.merch.inventory).reduce((a,x)=>a+x,0),cap=b.inventoryCap||800;if(inventory+pending+qty>cap)return mail(game,{sender:'Logística',subject:'Pedido de fabricación bloqueado',body:`No hay capacidad de almacén para este lote. Capacidad: ${cap.toLocaleString('es-ES')} uds contando pedidos pendientes.`,tone:'warning',screen:'merch'});const cmoDiscount=1-((game.staff.cmo?.rating??0)/1000),cost=Math.round(base*qty*cmoDiscount);if(game.cash<cost)return game;const days=clamp(2+Math.ceil(qty/550),3,28),process={id:uid('merch-prod',game,`${key}-${qty}`),type:'merchProduction',dueDay:game.day+days,payload:{key,qty,cost,days}};return {...game,cash:game.cash-cost,processes:[...game.processes,process],merch:{...game.merch,produced:{...game.merch.produced,[key]:(game.merch.produced[key]||0)+qty}},finance:{...game.finance,costs:game.finance.costs+cost}};}

export function setMediaProgram(game,patch){return {...game,mediaProgram:{...game.mediaProgram,...patch,channels:patch.channels?{...game.mediaProgram.channels,...patch.channels}:game.mediaProgram.channels}};}
export function scheduleEvent(game,type,dateISO){const d=eventCatalog[type];if(!d)return game;const target=Math.round((new Date(`${dateISO}T12:00:00Z`)-new Date(`${START_DATE}T12:00:00Z`))/DAY_MS);if(target<=game.day||target>game.day+240)return game;const deposit=Math.round(d.cost*.25);if(game.cash<deposit)return game;const event={id:uid('event',game,`${type}-${dateISO}`),type,day:target,dateISO,status:'scheduled',deposit};return {...game,cash:game.cash-deposit,events:[...game.events,event],finance:{...game.finance,costs:game.finance.costs+deposit}};}

export function signSupplier(game,category,candidate){const setup=candidate.setupFee||0;if(game.cash<setup)return game;let next=Base.signSupplier({...game,cash:game.cash-setup},category,candidate);next.finance={...next.finance,costs:next.finance.costs+setup};return next;}
export function startInvestment(game,type,amount,termDays=365){amount=Number(amount);if(amount<=0||game.cash<amount)return game;const inv={id:uid('investment',game,type),type,amount,termDays,startDay:game.day,dueDay:game.day+termDays,status:'active'};const process={id:`proc-${inv.id}`,type:'investment',dueDay:inv.dueDay,payload:{investmentId:inv.id}};return {...game,cash:game.cash-amount,financeV4:{...game.financeV4,investments:[...game.financeV4.investments,inv]},processes:[...game.processes,process]};}
export function takeDebt(game,amount){amount=Number(amount);if(amount<=0)return game;const cfo=game.staff.cfo?.rating||0;const rate=Math.max(.035,.065+debtRatio(game)*.055-cfo*.00018);const newRatio=(game.financeV4.debt+amount)/Math.max(1,annualRevenueEstimate(game));return {...game,cash:game.cash+amount,financeV4:{...game.financeV4,debt:game.financeV4.debt+amount,debtRate:rate},boardConfidence:clamp(game.boardConfidence-(newRatio>.5?4:1),0,100)};}
export function requestBoardCapital(game,amount){const process={id:uid('board-capital',game),type:'boardRequest',dueDay:game.day+3,payload:{kind:'capital',amount:Number(amount)}};return {...game,processes:[...game.processes,process]};}
export function requestObjectiveChange(game,objectiveId){const process={id:uid('board-objective',game,objectiveId),type:'boardRequest',dueDay:game.day+2,payload:{kind:'objective',objectiveId}};return {...game,processes:[...game.processes,process]};}

export function commissionFacilityProject(game,group,assetId,targetLevel){const current=game.infrastructure.levels[group]?.[assetId]||0,target=Number(targetLevel);if(target<=current||target>maxLevel(group,assetId))return game;if((game.processes||[]).some(p=>p.type==='facility'&&p.payload.group===group&&p.payload.assetId===assetId))return game;if((game.processes||[]).filter(p=>p.type==='facility').length>=game.infrastructure.maxProjects)return game;let cost=0,weeks=0;for(let i=current+1;i<=target;i++){const d=facilityDefs[group][assetId].levels[i];const req=d.requires||{};if(req.minCapacity&&game.stadium.capacity<req.minCapacity)return game;if(req.minBrand&&game.brandScore<req.minBrand)return game;cost+=d.cost;weeks+=d.weeks;}if(game.cash<cost)return game;const process={id:uid('facility',game,`${group}-${assetId}-${target}`),type:'facility',dueDay:game.day+weeks*7,payload:{group,assetId,targetLevel:target,startLevel:current,name:facilityDefs[group][assetId].levels[target].name,cost,weeks}};return {...game,cash:game.cash-cost,processes:[...game.processes,process],finance:{...game.finance,costs:game.finance.costs+cost,facilities:game.finance.facilities+cost}};}
export function activeFacilityProjects(game){return (game.processes||[]).filter(p=>p.type==='facility').map(p=>({...p.payload,id:p.id,dueDay:p.dueDay,remainingDays:p.dueDay-game.day}));}

export function setTrainingPlan(game,patch,force=false){if(game.staff.coach&&game.controlMode==='coach'&&!game.staff.coach.interim){const coach=game.staff.coach,rel=game.coachRelationship;const acceptance=clamp(30+game.gm.stats.tactics*2+rel.trust*.35+coach.flexibility*.3-coach.ego*.15,15,92);const roll=hashString(`${game.day}-${JSON.stringify(patch)}-${coach.id}`)%100;if(!force&&roll>acceptance)return mail(game,{sender:coach.name,subject:'Plan de entrenamiento rechazado',body:'El entrenador considera que cambiar la planificación esta semana perjudicaría su metodología.',tone:'warning',screen:'training'});const trust=clamp(rel.trust+(force?-6:1),0,100);return {...game,trainingPlan:{...game.trainingPlan,...patch},trainingIntensity:patch.intensity||game.trainingIntensity,coachRelationship:{...rel,trust}};}return {...game,trainingPlan:{...game.trainingPlan,...patch},trainingIntensity:patch.intensity||game.trainingIntensity};}
