import React,{useMemo,useState} from 'react';
import { SectionTitle, Metric, Pill, Bar } from '../components/UI.jsx';
import { sponsorPortfolio, money, getBrandScore, facilityBonuses } from '../game/engine.js';
import { merchChannelDefs } from '../data/management.js';
import contractsArt from '../assets/contracts.svg';
import merchArt from '../assets/merch-stand.svg';
import financeArt from '../assets/finance-office.svg';

export function BusinessOverview({game,setScreen}){
  const commercial=game.finance.sponsor+game.finance.merch+game.finance.hospitality+game.finance.events+game.finance.membership+game.finance.media;const areas=[
    ['sponsors','Patrocinios & partners','Derechos de camiseta, naming rights, partners oficiales y contratos de activación.',game.finance.sponsor,contractsArt],
    ['merch','Merchandising & licensing','Producto, stock, precio, canales, retail y distribución.',game.finance.merch,merchArt],
    ['hospitality','Hospitality & eventos','VIP, palcos, eventos no deportivos, restauración corporativa.',game.finance.hospitality+game.finance.events,financeArt],
    ['media','Media, miembros & CRM','Contenido, audiencia digital, membresías y monetización de la relación con el fan.',game.finance.media+game.finance.membership,financeArt],
    ['suppliers','Operaciones & procurement','Proveedores, calidad, contratos y coste operativo.',-game.finance.suppliers,contractsArt],
    ['finance','Finanzas','Caja, P&L, estructura de costes y capacidad para financiar el crecimiento.',game.cash,financeArt],
  ];
  return <><SectionTitle eyebrow="Negocio" title="El club como empresa" action={<Pill>Marca {getBrandScore(game)}/100</Pill>}/><div className="business-hero panel"><div><span>MOTOR COMERCIAL</span><h2>El resultado deportivo abre puertas. El negocio decide cuánto valen.</h2><p>En Primera Federación tus activos son locales. Si creces, aparecen partners nacionales, naming rights, distribución y media de otra escala.</p></div><Metric label="Ingresos comerciales" value={money(commercial)}/><Metric label="Sponsors activos" value={`${game.sponsors.length}`}/><Metric label="Miembros" value={game.business.membership.members.toLocaleString('es-ES')}/><Metric label="Alcance digital" value={game.business.media.digitalReach.toLocaleString('es-ES')}/></div><div className="business-area-grid">{areas.map(([id,title,desc,value,art])=><button key={id} className="business-area-card" onClick={()=>setScreen(id)}><img src={art} alt=""/><div><span>{title.toUpperCase()}</span><h3>{desc}</h3><b>{id==='finance'?money(value):`${value>=0?'+':''}${money(value)}`}</b></div><i>→</i></button>)}</div></>;
}

export function SponsorsV3({game,accept,submit}){
  const [deal,setDeal]=useState(null);const portfolio=sponsorPortfolio(game);const contracted=portfolio.filter(x=>x.contract),open=portfolio.filter(x=>!x.contract&&x.offers.length);const groups=['Kit','Naming rights','Partners','Local'];
  const offer=(slot,o)=>setDeal({slot,offer:o,annual:o.annual,round:1,message:`${o.brand} valora este derecho en torno a ${money(o.targetAnnual)} anuales.`});
  const negotiate=()=>{const r=submit(deal.offer,Number(deal.annual));if(r.status==='accepted')setDeal({...deal,stage:'accepted',message:r.message,offer:{...deal.offer,annual:Number(deal.annual)}});else if(r.status==='rejected')setDeal({...deal,round:deal.round+1,message:r.message});else setDeal({...deal,round:deal.round+1,message:r.message,offer:r.offer,annual:r.offer.targetAnnual});};
  const close=()=>setDeal(null);return <><SectionTitle eyebrow="Negocio · Patrocinios" title="Inventario de derechos comerciales" action={<Pill tone={game.club.tier>=3?'warning':'positive'}>{game.club.tier>=3?'Mercado local/regional':'Mercado ampliado'}</Pill>}/>
  <div className="sponsor-v3-hero"><img src={contractsArt} alt=""/><div><span>PORTFOLIO DE DERECHOS</span><h2>No existe “el patrocinador”</h2><p>Vendes activos diferentes: frontal, manga, ropa de entrenamiento, partners por categoría y —cuando la marca lo permite— naming rights. Cada contrato ocupa inventario y puede bloquear competidores del mismo sector.</p></div><div className="brand-meter"><small>FUERZA COMERCIAL</small><b>{game.brandScore}</b><Bar value={game.brandScore}/><span>Las multinacionales no aparecen porque sí: la escala del club limita quién ve valor en asociarse contigo.</span></div></div>
  {groups.map(group=><section key={group} className="sponsor-rights-section"><div className="section-inline-head"><div><span>{group.toUpperCase()}</span><h3>{group==='Kit'?'Equipación y entrenamiento':group==='Naming rights'?'Activos de naming':group==='Partners'?'Categorías oficiales':'Tejido empresarial local'}</h3></div></div><div className="rights-grid">{portfolio.filter(x=>x.group===group).map(slot=><article key={slot.id} className={`right-card ${slot.contract?'contracted':''}`}><div className="right-header"><span>{slot.short}</span>{slot.contract?<Pill tone="positive">Firmado</Pill>:<Pill>Disponible</Pill>}</div><h4>{slot.name}</h4>{slot.contract?<div className="contract-paper"><b>{slot.contract.brand}</b><span>{slot.contract.sector} · {slot.contract.scope}</span><div><small>ANUAL</small><strong>{money(slot.contract.annual)}</strong></div><div><small>DURACIÓN</small><strong>{slot.contract.years} años</strong></div><div><small>BONUS VICTORIA</small><strong>{money(slot.contract.bonusWin)}</strong></div></div>:slot.offers.length?<div className="offer-stack">{slot.offers.map(o=><button key={o.id} onClick={()=>offer(slot,o)}><div><b>{o.brand}</b><span>{o.scope} · {o.sector}</span></div><strong>{money(o.annual)}/año</strong></button>)}</div>:<div className="locked-right"><b>Sin mercado actualmente</b><span>Tu tamaño, categoría o marca todavía no generan una oferta creíble para este activo.</span></div>}</article>)}</div></section>)}
  {deal&&<div className="deal-overlay"><div className="sponsor-negotiation"><button className="deal-close" onClick={close}>×</button><div className="deal-brand-side"><span>{deal.slot.group}</span><h2>{deal.offer.brand}</h2><p>{deal.slot.name}</p><div className="brand-logo-fake">{deal.offer.brand.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><small>{deal.offer.scope.toUpperCase()} · {deal.offer.sector}</small></div><div className="deal-contract-side"><span>RONDA {deal.round}</span><h3>Negociación del derecho</h3><p>{deal.message}</p><div className="contract-terms"><div><span>Duración</span><b>{deal.offer.years} años</b></div><div><span>Bonus victoria</span><b>{money(deal.offer.bonusWin)}</b></div><div><span>Activación esperada</span><b>{money(deal.offer.activationAsk)}</b></div></div>{deal.stage==='accepted'?<><div className="negotiation-message">Acuerdo económico alcanzado en {money(deal.offer.annual)} por temporada.</div><button className="primary wide" onClick={()=>{accept(deal.offer);close();}}>Firmar contrato</button></>:<><label className="deal-input"><span>Tu propuesta anual</span><input type="number" step="5000" value={deal.annual} onChange={e=>setDeal({...deal,annual:e.target.value})}/></label><button className="primary wide" onClick={negotiate}>Enviar propuesta</button></>}</div></div></div>}</>;
}

export function MerchV3({game,produce,upgradeChannel,setPrice}){
  const [qty,setQty]=useState({shirt:100,scarf:100,cap:100});const products=[['shirt','Camiseta',17],['scarf','Bufanda',6],['cap','Gorra',8]];const inv=Object.values(game.merch.inventory).reduce((a,b)=>a+b,0);const cap=facilityBonuses(game).inventoryCap||800;
  return <><SectionTitle eyebrow="Negocio · Merchandising" title="Producto, stock y canales" action={<Pill>{inv.toLocaleString('es-ES')}/{cap.toLocaleString('es-ES')} uds almacén</Pill>}/><div className="merch-v3-hero"><img src={merchArt} alt=""/><div><span>OPERACIÓN DE RETAIL</span><h2>Fabricar más no significa vender más</h2><p>El capital queda inmovilizado en inventario. Los canales tienen capacidad. El almacén tiene límites. Y la tienda del estadio solo merece la pena cuando existe demanda.</p></div><Metric label="Ventas temporada" value={money(game.merch.revenueSeason)}/></div>
  <h3 className="minor-title">Catálogo y producción</h3><div className="product-v3-grid">{products.map(([id,name,cost])=><article key={id}><div className={`product-visual pv-${id}`}><span>{name}</span></div><h3>{name}</h3><div className="product-stats"><span>Stock <b>{game.merch.inventory[id]}</b></span><span>Coste base <b>{money(cost)}</b></span></div><label>Precio de venta<input type="number" min="1" value={game.merch.prices[id]} onChange={e=>setPrice(id,e.target.value)}/></label><label>Lote a fabricar<input type="number" min="1" step="50" value={qty[id]} onChange={e=>setQty({...qty,[id]:Number(e.target.value)})}/></label><button className="primary wide" onClick={()=>produce(id,qty[id])}>Producir {qty[id]} uds</button></article>)}</div>
  <h3 className="minor-title">Canales de venta</h3><div className="channel-grid">{Object.entries(merchChannelDefs).map(([id,d])=>{const level=game.merch.channels[id]||0,current=d.levels[level],next=d.levels[level+1];return <article key={id}><span>CANAL</span><h3>{d.name}</h3><b>{current.name}</b><p>{current.description}</p><div className="channel-cap">Capacidad orientativa <strong>{current.capacity.toLocaleString('es-ES')} uds/sem.</strong></div>{next?<div className="channel-next"><small>Siguiente</small><b>{next.name}</b><span>{next.description}</span><button onClick={()=>upgradeChannel(id)}>Invertir {money(next.cost)}</button></div>:<Pill tone="positive">Máximo desarrollo</Pill>}</article>})}</div></>;
}

export function HospitalityV3({game,setPolicy}){
  const b=facilityBonuses(game),h=game.business.hospitality;const eventPolicies=[['none','Sin eventos','Proteges el césped y evitas complejidad.'],['community','Comunitario','Eventos locales de bajo riesgo y menor margen.'],['commercial','Comercial','Más uso fuera de partido, más ingreso y coste.'],['aggressive','Máxima explotación','Agenda intensa. Potencial alto, más presión operativa.']];
  return <><SectionTitle eyebrow="Negocio · Hospitality" title="VIP, palcos y explotación no deportiva"/><div className="hospitality-hero panel"><div className="hospitality-suite-art"><i/><i/><i/><span>HOSPITALITY</span></div><div><span>DEPENDIENTE DEL ACTIVO</span><h2>No puedes vender un palco que no has construido</h2><p>La pantalla comercial se conecta al master plan del estadio: VIP, restauración, retail y espacios no-match determinan el producto que puedes vender.</p></div><Metric label="Capacidad VIP" value={game.stadium.vipSeats}/><Metric label="Potencia hospitality" value={`+${b.hospitality||0}`}/><Metric label="Negocio no-match" value={`+${b.nonMatch||0}`}/></div><div className="hospitality-controls"><article className="panel"><span>PRECIO VIP</span><h3>Precio por invitado / partido</h3><input type="range" min="35" max="350" step="5" value={h.vipPrice} onChange={e=>setPolicy('hospitality',{vipPrice:Number(e.target.value)})}/><b>{money(h.vipPrice)}</b><p>Un club pequeño puede tener mejores resultados llenando una sala sencilla que intentando cobrar precio Champions.</p></article><article className="panel"><span>EVENTOS FUERA DE PARTIDO</span><h3>Política de explotación</h3><div className="policy-options">{eventPolicies.map(([id,name,desc])=><button className={h.eventPolicy===id?'selected':''} key={id} onClick={()=>setPolicy('hospitality',{eventPolicy:id})}><b>{name}</b><span>{desc}</span></button>)}</div></article></div></>;
}

export function MediaV3({game,setPolicy}){
  const m=game.business.media,mem=game.business.membership,b=facilityBonuses(game);return <><SectionTitle eyebrow="Negocio · Media & CRM" title="Convertir aficionados en una relación directa" action={<Pill>{m.digitalReach.toLocaleString('es-ES')} alcance digital</Pill>}/><div className="media-dashboard"><article className="media-studio-card"><div className="studio-scene"><div className="camera"/><div className="desk"/><div className="screen">CLUB TV</div></div><span>MEDIA CENTER</span><h3>Capacidad de contenido +{b.media||0}</h3><p>La instalación física limita la calidad y frecuencia de contenido. Un gran equipo comercial sin media center deja valor sobre la mesa.</p></article><article className="panel"><span>PRESUPUESTO SEMANAL DE CONTENIDO</span><h3>{money(m.weeklyBudget)}/semana</h3><input type="range" min="0" max="20000" step="250" value={m.weeklyBudget} onChange={e=>setPolicy('media',{weeklyBudget:Number(e.target.value)})}/><p>Más presupuesto acelera crecimiento digital, pero se convierte en un coste fijo incluso cuando el equipo pierde.</p><Bar value={Math.min(100,(m.weeklyBudget/20000)*100)} label="Intensidad de inversión"/></article><article className="panel"><span>MEMBRESÍA DEL CLUB</span><h3>{mem.members.toLocaleString('es-ES')} miembros</h3><label className="membership-fee">Cuota anual<input type="number" min="5" max="500" step="5" value={mem.annualFee} onChange={e=>setPolicy('membership',{annualFee:Number(e.target.value)})}/></label><p>Una cuota alta monetiza al fan fiel; una baja amplía base, datos y capacidad futura de venta.</p><Metric label="Ingreso anual teórico" value={money(mem.members*mem.annualFee)}/></article></div></>;
}
