import React from 'react';
import {SectionTitle,Bar,Pill,Metric} from '../components/UI.jsx';
import {TacticPitch,MiniRadar} from '../components/Visual.jsx';
import {getActiveTactic,getCoachRequests,getFanTacticalSatisfaction,squadTacticalFit,money} from '../game/engine.js';
import {tacticalPresets,formations} from '../data/names.js';
import {coachInterventions} from '../data/management.js';
import tacticsArt from '../assets/tactics-board.svg';
const controls=[['transitionDA','Transición defensa → ataque'],['transitionAD','Transición ataque → defensa'],['freedom','Libertad posicional'],['defensiveLine','Altura línea defensiva'],['pressing','Presión'],['aggression','Agresividad'],['directness','Verticalidad'],['tempo','Ritmo'],['width','Amplitud'],['setPieces','Peso balón parado'],['attackIntent','Vocación ofensiva']];
export default function Coach({game,setGame,hire,setTactic,preset,intervene,fire}){
  const t=getActiveTactic(game),coach=game.staff.coach,fanFit=getFanTacticalSatisfaction(game),requests=getCoachRequests(game),editable=game.controlMode==='self',intensity=Math.round((t.pressing+t.aggression+t.transitionAD)/3),rel=game.coachRelationship||{trust:0,respect:0};
  return <><SectionTitle eyebrow="Área deportiva" title="Entrenador, modelo de juego y poder" action={<Pill tone={fanFit>=75?'positive':fanFit<50?'negative':'warning'}>Afición {fanFit}%</Pill>}/>
  <div className="coach-power-hero"><div className="coach-power-art"><img src={tacticsArt} alt=""/><div className="coach-silhouette"><i/><i/></div></div><div className="coach-power-copy"><span>RELACIÓN GM ↔ ENTRENADOR</span><h2>{editable?'Tú eres el entrenador':coach?coach.name:'Banquillo vacante'}</h2><p>{editable?'Control total: nadie puede rechazar tus instrucciones, pero el rendimiento táctico depende de tu capacidad.':coach?'Contratarlo no te convierte en su dueño. Puedes sugerir, presionar o imponer; su reputación, ego, flexibilidad y vuestra relación deciden cuánto tolera.':'Sin entrenador, deberás contratar uno o asumir el banquillo.'}</p></div>{!editable&&coach?<div className="coach-rel-kpis"><Metric label="Confianza" value={`${rel.trust}%`}/><Metric label="Respeto" value={`${rel.respect}%`}/><Metric label="Reputación técnico" value={coach.reputation}/><Metric label="Flexibilidad" value={coach.flexibility}/></div>:<div className="coach-rel-kpis"><Metric label="Táctica GM" value={`${game.gm.stats.tactics}/20`}/><Metric label="Fútbol GM" value={`${game.gm.stats.football}/20`}/><Metric label="Carga" value={game.trainingIntensity}/></div>}</div>
  <div className="mode-switch richer"><button className={game.controlMode==='coach'?'selected':''} onClick={()=>setGame({...game,controlMode:'coach'})}><b>Delegar en entrenador</b><span>El técnico tiene autoridad real. Intervenir puede ayudar o romper la relación.</span></button><button className={game.controlMode==='self'?'selected':''} onClick={()=>setGame({...game,controlMode:'self'})}><b>Control total del GM</b><span>Defines fútbol, entrenamiento y prioridades directamente.</span></button></div>
  <div className="tactics-layout"><article className="panel tactic-visual"><div className="coach-banner"><img src={tacticsArt} alt=""/><div><span>{editable?'TU MODELO':'MODELO DEL ENTRENADOR'}</span><h3>{editable?'Sistema del GM':coach?.name||'Sin entrenador'}</h3><p>{editable?'Puedes modificar todos los parámetros.':coach?`${coach.trait} · ${coach.tactic?.name}`:'Contrata un técnico para delegar.'}</p></div></div><TacticPitch formation={t.formation}/><div className="formation-picker"><label>Formación<select value={t.formation} disabled={!editable} onChange={e=>setTactic({formation:e.target.value})}>{formations.map(f=><option key={f}>{f}</option>)}</select></label><div><span>ENCAJE XI</span><strong>{squadTacticalFit(game)}%</strong></div></div></article>
  <article className="panel tactic-controls"><div className="panel-head"><div><span>INSTRUCCIONES</span><h3>Parámetros tácticos</h3></div>{!editable&&<Pill>Propiedad del técnico</Pill>}</div>{editable&&<div className="preset-strip">{tacticalPresets.map(p=><button key={p.id} onClick={()=>preset(p.id)}>{p.name}</button>)}</div>}{controls.map(([key,label])=><label className="tactic-slider" key={key}><span>{label}<b>{Math.round(t[key])}/20</b></span><input type="range" min="1" max="20" value={t[key]} disabled={!editable} onChange={e=>setTactic({[key]:Number(e.target.value)})}/></label>)}</article></div>
  <div className="coach-management-grid"><article className="panel"><div className="panel-head"><div><span>REUNIÓN CON EL ENTRENADOR</span><h3>Intervenir sin tomar el banquillo</h3></div></div><p className="muted-copy">Una sugerencia puede ser rechazada. Una orden se aplica, pero erosiona la relación; un técnico prestigioso puede terminar dimitiendo.</p><div className="intervention-list">{Object.entries(coachInterventions).map(([id,a])=><div key={id} className="intervention-row"><div><b>{a.label}</b><span>{a.detail}</span></div><button disabled={editable||!coach} onClick={()=>intervene(id,false)}>Sugerir</button><button className="danger-ghost" disabled={editable||!coach} onClick={()=>intervene(id,true)}>Exigir</button></div>)}</div>{coach&&!editable&&<button className="fire-button" onClick={fire}>Destituir entrenador · indemnización aprox. {money(coach.salary*(.18+.08*(coach.contractYears||1)))}</button>}</article>
  <article className="panel"><div className="panel-head"><div><span>DESPACHO DEL ENTRENADOR</span><h3>Lo que él te pide a ti</h3></div></div>{editable?<div className="empty">No hay contraparte: el GM controla el área deportiva.</div>:requests.length?requests.map(r=><div className="coach-request" key={r.id}><Pill tone={r.fulfilled?'positive':r.priority==='Alta'?'warning':'neutral'}>{r.fulfilled?'Cumplida':r.priority}</Pill><div><b>{r.title}</b><span>{r.detail}</span></div></div>):<div className="empty">El entrenador considera que la estructura actual cubre sus necesidades inmediatas.</div>}<div className="training-status"><span>CARGA ACTUAL</span><b>{game.trainingIntensity==='high'?'Alta':game.trainingIntensity==='light'?'Ligera':'Equilibrada'}</b><p>Alta: más sharpness/desarrollo, peor frescura y mayor riesgo de lesión. Ligera: mejor recuperación, menos ritmo.</p></div></article></div>
  <div className="tactics-bottom"><article className="panel culture-card"><div><span>IDENTIDAD DE LA GRADA</span><h3>{game.fanCulture.name}</h3><p>La afición no exige una formación concreta. Evalúa ambición, creatividad, intensidad y tradición.</p></div><MiniRadar values={[game.fanCulture.attack,game.fanCulture.freedom,game.fanCulture.intensity,game.fanCulture.youth]} labels={['Ataque','Libertad','Intensidad','Cantera']}/><div className="culture-compare"><Bar label="Vocación ofensiva" value={t.attackIntent} max={20}/><Bar label="Libertad" value={t.freedom} max={20}/><Bar label="Intensidad" value={intensity} max={20}/><strong>Compatibilidad global: {fanFit}%</strong></div></article></div>
  {game.controlMode==='coach'&&<><h3 className="minor-title">Mercado de entrenadores</h3><div className="card-grid coaches">{game.coachCandidates.map(c=><article className="person-card coach-market" key={c.id}><div className="person-top"><div className="avatar">{c.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div><h4>{c.name}</h4><span>{c.trait} · {c.specialty}</span></div></div><TacticPitch formation={c.tactic.formation} compact/><b>{c.tactic.name}</b><div className="coach-traits"><span>Reputación <b>{c.reputation}</b></span><span>Ego <b>{c.ego}</b></span><span>Flexibilidad <b>{c.flexibility}</b></span></div><Bar value={c.rating} label="Rating"/><div className="card-foot"><span>{money(c.salary)}/año</span><button onClick={()=>hire('Entrenador',c)}>Contratar</button></div></article>)}</div></>}</>;
}
