import React from 'react';import {Initials,Metric,Pill,Bar} from '../components/UI.jsx';import {money,getFanTacticalSatisfaction,squadTacticalFit} from '../game/engine.js';
import stadiumArt from '../assets/stadium-aerial.svg';import tacticsArt from '../assets/tactics-board.svg';import staffArt from '../assets/staff-room.svg';import financeArt from '../assets/finance-office.svg';
export default function Dashboard({game,onOpen}){const position=game.table.findIndex(x=>x.id===game.club.id)+1;const next=game.schedule[game.week-1];const cats=[
{id:'sport',art:tacticsArt,title:'DEPORTIVO',lead:'Modelo, plantilla y mercado',metric:`${position}º · Encaje XI ${squadTacticalFit(game)}%`},
{id:'club',art:staffArt,title:'CLUB & DIRECTIVA',lead:'Personas, confianza y carrera',metric:`Confianza ${Math.round(game.boardConfidence)}%`},
{id:'business',art:financeArt,title:'FINANZAS & NEGOCIO',lead:'Caja, sponsors, retail y contratos',metric:`Caja ${money(game.cash)}`},
{id:'matchday',art:stadiumArt,title:'MATCH DAY',lead:'Estadio, afición y explotación',metric:`${game.stadium.capacity.toLocaleString('es-ES')} plazas`},
];return <>
<section className="command-hero"><div className="command-copy"><div className="kicker">Centro de mando</div><h1>{game.club.name}</h1><p>{game.gm.name} · General Manager. Cada semana compites en dos ligas: la clasificación deportiva y la capacidad del club para crecer.</p><div className="command-metrics"><Metric label="Posición" value={`${position}º`}/><Metric label="Caja" value={money(game.cash)}/><Metric label="Afición" value={`${Math.round(game.fanSentiment)}%`}/><Metric label="Estilo" value={`${getFanTacticalSatisfaction(game)}% fit`}/></div></div>
<div className="hub-visual"><img src={stadiumArt} alt="Vista esquemática del estadio"/><div className="hub-ring"><span>DEP</span><span>CLUB</span><span>€</span><span>MD</span></div></div>
<div className="next-match-card"><span>PRÓXIMO PARTIDO</span>{next?<><div className="match-row"><Initials name={next.home?game.club.name:next.opponent} size="sm"/><b>{next.home?game.club.name:next.opponent}</b><em>vs</em><Initials name={next.home?next.opponent:game.club.name} size="sm"/><b>{next.home?next.opponent:game.club.name}</b></div><Pill tone={next.home?'positive':'neutral'}>{next.home?'En casa':'Fuera'}</Pill></>:<b>Temporada regular completada</b>}</div></section>
<section className="management-grid">{cats.map(c=><button key={c.id} className={`management-tile ${c.id}`} onClick={()=>onOpen(c.id)}><img src={c.art} alt=""/><div className="tile-shade"/><div className="tile-copy"><span>{c.title}</span><h3>{c.lead}</h3><b>{c.metric}</b></div><i>↗</i></button>)}</section>
<section className="dashboard-lower"><article className="panel"><div className="panel-head"><div><span>SEMANA EN EL CLUB</span><h3>Últimas noticias</h3></div></div><div className="news-list">{game.news.slice(0,7).map((n,i)=><div key={`${n.week}-${i}`}><span className={`news-dot ${n.tone}`}/><div><b>{n.title}</b><small>Semana {n.week}</small></div></div>)}</div></article><article className="panel"><div className="panel-head"><div><span>PULSO DEL PROYECTO</span><h3>No todo es la tabla</h3></div></div><Bar label="Directiva" value={game.boardConfidence}/><Bar label="Afición" value={game.fanSentiment}/><Bar label="Encaje táctico de la plantilla" value={squadTacticalFit(game)}/><Bar label="Satisfacción de estilo" value={getFanTacticalSatisfaction(game)}/></article></section>
</>}
