import React from 'react';
import { SectionTitle, Metric, Pill } from '../components/UI.jsx';
import { money } from '../game/engine.js';
import financeArt from '../assets/finance-office.svg';

export default function FinanceV3({game}){
  const f=game.finance;const operating=f.revenue-f.costs;const revenues=[['Entradas & abonos',f.ticket],['Patrocinios',f.sponsor],['Merchandising',f.merch],['Hospitality',f.hospitality],['Eventos',f.events],['Locales comerciales',f.commercialSpaces||0],['Membresías',f.membership],['Media/digital',f.media],['TV / competición',f.broadcast]];const costs=[['Salarios',f.wages],['Instalaciones / CAPEX + OPEX',f.facilities],['Proveedores',f.suppliers],['Fichajes',f.transfersIn]];
  return <><SectionTitle eyebrow="Negocio · Finanzas" title="Tesorería, P&L y capacidad de inversión" action={<Pill tone={game.cash<0?'negative':operating>0?'positive':'warning'}>{money(game.cash)} caja</Pill>}/><div className="finance-v3-hero"><img src={financeArt} alt=""/><div><span>DISCIPLINA FINANCIERA</span><h2>Puedes crecer demasiado rápido</h2><p>El juego no protege al GM de una mala decisión. Una ciudad deportiva magnífica, contratos caros y un estadio sobredimensionado pueden arruinar un proyecto deportivamente sano.</p></div><Metric label="Ingresos acumulados" value={money(f.revenue)}/><Metric label="Costes acumulados" value={money(f.costs)}/><Metric label="Resultado operativo" value={money(operating)} tone={operating>=0?'positive':'negative'}/></div><div className="finance-columns"><article className="panel"><div className="panel-head"><div><span>INGRESOS</span><h3>De dónde viene el dinero</h3></div></div>{revenues.map(([n,v])=><div className="finance-line" key={n}><span>{n}</span><b>{money(v||0)}</b></div>)}</article><article className="panel"><div className="panel-head"><div><span>COSTES</span><h3>Dónde se consume</h3></div></div>{costs.map(([n,v])=><div className="finance-line" key={n}><span>{n}</span><b>{money(v||0)}</b></div>)}</article></div><article className="panel cash-history"><span>ÚLTIMAS SEMANAS</span><div className="cash-spark">{f.weekly.slice(-14).map(w=>{const h=Math.min(100,Math.max(6,50+(w.revenue-w.costs)/12000));return <div key={w.week}><i style={{height:`${h}%`}}/><small>S{w.week}</small></div>})}</div></article></>;
}
