import React,{useState} from 'react';import {SectionTitle,Metric,Pill} from '../components/UI.jsx';import {commercialUnitCatalog,money} from '../game/engine.js';import stadiumArt from '../assets/stadium-aerial.svg';import infrastructureArt from '../assets/infrastructure.svg';
const upgrades=[
{id:'barcode',name:'Accesos digitalizados',desc:'Sustituye control manual por lectura de códigos. Más flujo y mejor experiencia.',hint:'Especialmente útil cuando empiezas a acercarte al lleno.'},
{id:'automatic',name:'Tornos automáticos',desc:'Acceso moderno de alta capacidad. Requiere inversión fuerte.',hint:'No tiene sentido en muchos campos pequeños.'},
{id:'gates',name:'Añadir accesos',desc:'Dos nuevos puntos de entrada reducen cuellos de botella.',hint:'Escala con el tamaño del estadio.'},
{id:'concourse',name:'Galería comercial',desc:'Mejora circulación interior y añade un slot comercial.',hint:'Convierte espacio físico en nuevas líneas de ingreso.'},
{id:'transport',name:'Accesibilidad exterior',desc:'Parking, señalización y coordinación de transporte público.',hint:'Aumenta la capacidad real de atraer público.'},
{id:'seats',name:'Ampliar aforo',desc:'Añade aproximadamente un 14% de asientos.',hint:'Mala inversión si el campo no se llena.'},
];
export default function Stadium({game,upgrade,buildUnit}){const [buildSlot,setBuildSlot]=useState(null);const s=game.stadium;return <><SectionTitle eyebrow="Match day" title="Estadio como infraestructura y negocio" action={<Pill>{s.access}</Pill>}/>
<div className="stadium-command"><article className="stadium-map"><img src={stadiumArt} alt="Plano aéreo esquemático del estadio"/><div className="stadium-map-label"><span>{game.club.name}</span><strong>{s.capacity.toLocaleString('es-ES')}</strong><small>plazas</small></div>{Array.from({length:s.commercialSlots}).map((_,i)=>{const u=s.units.find(x=>x.slot===i);return <button key={i} className={`stadium-slot slot-${i} ${u?'occupied':''}`} onClick={()=>!u&&setBuildSlot(i)}><b>{u?commercialUnitCatalog[u.type].name:'+'}</b><span>{u?'Operativo':'Local vacío'}</span></button>})}</article>
<aside className="stadium-systems"><Metric label="Accesos" value={`${s.accessRating}/100`} sub={`${s.gates} puntos de entrada`}/><Metric label="Galería" value={`Nivel ${s.concourse}`} sub={`${s.commercialSlots} espacios comerciales`}/><Metric label="Transporte" value={`${s.transport}/100`}/><Metric label="Estado" value={`${s.condition}%`}/><div className="system-note"><img src={infrastructureArt} alt=""/><p>El aforo teórico no sirve si los accesos, transporte y servicios no pueden manejar la demanda.</p></div></aside></div>
<h3 className="minor-title">Plan director del estadio</h3><div className="upgrade-grid stadium-upgrades">{upgrades.map(u=><article key={u.id}><span>INFRAESTRUCTURA</span><h3>{u.name}</h3><p>{u.desc}</p><small>{u.hint}</small><button className="primary" onClick={()=>upgrade(u.id)}>Evaluar y ejecutar</button></article>)}</div>
{buildSlot!==null&&<div className="deal-overlay"><div className="unit-builder"><button className="deal-close" onClick={()=>setBuildSlot(null)}>×</button><span>ESPACIO COMERCIAL {buildSlot+1}</span><h2>¿Qué construimos?</h2><p>El mismo metro cuadrado puede maximizar caja estable, gasto por aficionado o crecimiento de marca.</p><div className="unit-options">{Object.entries(commercialUnitCatalog).map(([id,d])=><button key={id} onClick={()=>{buildUnit(buildSlot,id);setBuildSlot(null)}}><b>{d.name}</b><span>Construcción {money(d.build)}</span><small>{id==='rental'?'Ingreso estable, poco upside.':id==='clubShop'?'Impulsa merchandising y marca.':id==='restaurant'?'Más gasto por asistente, más coste fijo.':id==='hospitality'?'Alto margen si existe demanda corporativa.':'Barato y flexible para empezar.'}</small></button>)}</div></div></div>}</>}
