import React from 'react';
import { SectionTitle, Metric, Bar, Pill } from '../components/UI.jsx';
import { ticketProjection, money, facilityBonuses } from '../game/engine.js';

export default function TicketingV3({game,updateZone}){
  const p=ticketProjection(game),b=facilityBonuses(game);return <><SectionTitle eyebrow="Infraestructura · Estadio" title="Ticketing y abonos por zona" action={<Pill tone={p.attendance>game.stadium.capacity*.9?'positive':'neutral'}>{Math.round(p.attendance/game.stadium.capacity*100)}% ocupación prevista</Pill>}/>
  <div className="ticket-hero panel"><div><span>POLÍTICA DE PRECIOS</span><h3>No vendes “una entrada”: vendes inventario diferente</h3><p>Decide cuánto aforo blindas como abono, qué precio anual cobras y cuánto dejas para taquilla en cada zona. Mejorar asientos, baños, accesos y pantallas aumenta lo que el aficionado está dispuesto a pagar.</p></div><Metric label="Asistencia prevista" value={p.attendance.toLocaleString('es-ES')} sub={`de ${game.stadium.capacity.toLocaleString('es-ES')}`}/><Metric label="Ingreso por partido" value={money(p.revenue)}/><Metric label="Efecto instalaciones" value={`+${(b.ticketWtp||0).toFixed(1)} WTP`}/></div>
  <div className="ticket-zone-grid">{p.zones.map(z=><article className="ticket-zone-card" key={z.id}><div className="zone-diagram"><div className={`zone-pitch zone-${z.id}`}/><span>{z.name}</span><b>{z.capacity.toLocaleString('es-ES')} plazas</b></div><div className="ticket-zone-body"><div className="zone-kpis"><Metric label="Abonos previstos" value={z.seasonSold.toLocaleString('es-ES')}/><Metric label="Taquilla prevista" value={z.regularSold.toLocaleString('es-ES')}/></div><label className="policy-control"><span>Precio partido <b>{money(z.matchPrice)}</b></span><input type="range" min="5" max="90" step="1" value={z.matchPrice} onChange={e=>updateZone(z.id,{matchPrice:Number(e.target.value)})}/></label><label className="policy-control"><span>Precio abono <b>{money(z.seasonPrice)}</b></span><input type="range" min="80" max="1200" step="10" value={z.seasonPrice} onChange={e=>updateZone(z.id,{seasonPrice:Number(e.target.value)})}/></label><label className="policy-control"><span>Aforo ofrecido en abonos <b>{Math.round(z.seasonAllocation*100)}%</b></span><input type="range" min="5" max="80" step="5" value={Math.round(z.seasonAllocation*100)} onChange={e=>updateZone(z.id,{seasonAllocation:Number(e.target.value)/100})}/></label><Bar value={z.attendance} max={z.capacity} label="Ocupación prevista"/><div className="zone-revenue">Ingreso equivalente por partido <b>{money(z.revenue)}</b></div></div></article>)}</div>
  <div className="ticket-principles panel"><div><b>Precio alto</b><span>Más ingreso por asiento, menor demanda y menor margen para una mala racha.</span></div><div><b>Muchos abonos</b><span>Caja y asistencia estable, pero menos inventario para monetizar grandes partidos.</span></div><div><b>Infraestructura premium</b><span>Puede sostener precios mayores, pero el CAPEX tarda años en recuperarse.</span></div></div></>;
}
