import React,{useMemo,useState} from 'react';import {SectionTitle,SortHeader,Pill,Bar} from '../components/UI.jsx';import {money,playerTacticalFit,getActiveTactic} from '../game/engine.js';import transferArt from '../assets/transfer-room.svg';
export default function Transfers({game,evaluateClub,evaluatePlayer,complete}){const [sort,setSort]=useState({key:'overall',dir:'desc'}),[filter,setFilter]=useState(''),[deal,setDeal]=useState(null);const tactic=getActiveTactic(game);
const rows=useMemo(()=>game.market.filter(p=>!filter||p.pos===filter).map(p=>({...p,fit:playerTacticalFit(p,tactic)})).sort((a,b)=>{const av=a[sort.key],bv=b[sort.key];return (typeof av==='string'?av.localeCompare(bv):av-bv)*(sort.dir==='asc'?1:-1)}),[game.market,sort,filter,tactic]);const onSort=key=>setSort({key,dir:sort.key===key&&sort.dir==='desc'?'asc':'desc'});
const open=p=>setDeal({player:p,stage:p.club==='Libre'?'player':'club',clubRound:1,clubFee:p.club==='Libre'?0:Math.round(p.seller.asking*.72/50000)*50000,clubMessage:'Presenta una primera propuesta. Una oferta baja protege caja, pero puede deteriorar la negociación.',salary:p.agent.salaryAsk*.84,signing:p.agent.signingAsk*.75,playerRound:1,playerMessage:'Después del club tendrás que convencer al jugador y su agente.'});
const offerClub=()=>{const r=evaluateClub(deal.player,Number(deal.clubFee),deal.clubRound);if(r.status==='accepted')setDeal({...deal,stage:'player',clubMessage:r.message});else if(r.status==='walked')setDeal({...deal,stage:'failed',clubMessage:r.message});else setDeal({...deal,clubRound:deal.clubRound+1,clubMessage:r.message,clubFee:r.counter||deal.clubFee});};
const offerPlayer=()=>{const r=evaluatePlayer(deal.player,Number(deal.salary),Number(deal.signing),deal.playerRound);if(r.status==='accepted')setDeal({...deal,stage:'ready',playerMessage:r.message});else if(r.status==='walked')setDeal({...deal,stage:'failed',playerMessage:r.message});else setDeal({...deal,playerRound:deal.playerRound+1,playerMessage:r.message,salary:r.salary||deal.salary,signing:r.signing||deal.signing});};
const finish=()=>{complete(deal.player,Number(deal.clubFee),Number(deal.salary),Number(deal.signing));setDeal(null)};
return <><SectionTitle eyebrow="Área deportiva" title="Mercado y negociación" action={<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Todas las posiciones</option>{['POR','LD','DFC','LI','MCD','MC','MP','ED','EI','DC'].map(x=><option key={x}>{x}</option>)}</select>}/>
<div className="transfer-intro panel"><img src={transferArt} alt=""/><div><span>SALA DE OPERACIONES</span><h3>El precio de mercado no es el precio del acuerdo</h3><p>Cada fichaje pasa por negociación con club y agente. Tu habilidad, su paciencia, necesidad de vender y la agresividad de tu oferta cambian el resultado.</p></div><div><b>{game.gm.stats.players}/20</b><span>Negociación jugadores</span></div></div>
<div className="panel table-panel"><table><thead><tr><th>Jugador</th><th>Pos</th><th>Tipo</th><th><SortHeader label="OVR" sortKey="overall" current={sort} onSort={onSort}/></th><th><SortHeader label="Techo" sortKey="potential" current={sort} onSort={onSort}/></th><th><SortHeader label="Encaje" sortKey="fit" current={sort} onSort={onSort}/></th><th><SortHeader label="Valor" sortKey="value" current={sort} onSort={onSort}/></th><th>Situación</th><th></th></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td><b>{p.name}</b>{p.star&&<small><Pill tone="warning">Estrella relativa</Pill></small>}</td><td>{p.pos}</td><td>{p.archetype}</td><td><strong className="rating">{p.overall}</strong></td><td>{p.potential}</td><td><span className={`fit-score ${p.fit>=75?'good':p.fit<55?'bad':''}`}>{p.fit}%</span></td><td>{money(p.value)}</td><td>{p.club==='Libre'?'Libre':p.listed?'Transferible':p.club}</td><td><button className="table-action" onClick={()=>open(p)}>Negociar</button></td></tr>)}</tbody></table></div>
{deal&&<div className="deal-overlay" role="dialog" aria-modal="true"><div className="deal-room"><button className="deal-close" onClick={()=>setDeal(null)}>×</button><div className="deal-art"><img src={transferArt} alt=""/><Pill>{deal.player.pos}</Pill><h2>{deal.player.name}</h2><p>{deal.player.archetype} · OVR {deal.player.overall} · Encaje {playerTacticalFit(deal.player,tactic)}%</p><div className="deal-kpis"><span><small>Valor estimado</small><b>{money(deal.player.value)}</b></span><span><small>Tu caja</small><b>{money(game.cash)}</b></span><span><small>Skill GM</small><b>{game.gm.stats.players}/20</b></span></div></div><div className="deal-body"><div className="deal-steps"><span className={['club','player','ready'].includes(deal.stage)?'active':''}>1 Club</span><span className={['player','ready'].includes(deal.stage)?'active':''}>2 Jugador</span><span className={deal.stage==='ready'?'active':''}>3 Firma</span></div>
{deal.stage==='club'&&<><h3>Negociar traspaso</h3><p>El club pide públicamente alrededor de <b>{money(deal.player.seller.asking)}</b>. No conoces su mínimo real.</p><label className="deal-input"><span>Oferta al club</span><input type="number" step="50000" value={Math.round(deal.clubFee)} onChange={e=>setDeal({...deal,clubFee:e.target.value})}/></label><Bar label="Paciencia consumida" value={deal.clubRound-1} max={deal.player.seller.patience}/><div className="negotiation-message">{deal.clubMessage}</div><button className="primary wide" onClick={offerClub}>Enviar oferta · ronda {deal.clubRound}</button></>}
{deal.stage==='player'&&<><h3>Contrato del jugador</h3><p>Acuerdo con club: <b>{money(deal.clubFee)}</b>. Ahora el agente evalúa salario y prima conjuntamente.</p><div className="deal-two"><label className="deal-input"><span>Salario anual</span><input type="number" step="5000" value={Math.round(deal.salary)} onChange={e=>setDeal({...deal,salary:e.target.value})}/></label><label className="deal-input"><span>Prima de firma</span><input type="number" step="5000" value={Math.round(deal.signing)} onChange={e=>setDeal({...deal,signing:e.target.value})}/></label></div><Bar label="Paciencia del agente" value={deal.playerRound-1} max={deal.player.agent.patience}/><div className="negotiation-message">{deal.playerMessage}</div><button className="primary wide" onClick={offerPlayer}>Presentar contrato · ronda {deal.playerRound}</button></>}
{deal.stage==='ready'&&<><h3>Acuerdo total</h3><div className="agreement-box"><span>Traspaso <b>{money(deal.clubFee)}</b></span><span>Prima <b>{money(deal.signing)}</b></span><span>Salario <b>{money(deal.salary)}/año</b></span></div><p>No existe una respuesta universalmente correcta: cerrar rápido reduce riesgo, negociar duro protege caja, y cada euro gastado aquí no va a staff o infraestructura.</p><button className="primary wide" disabled={game.cash<Number(deal.clubFee)+Number(deal.signing)} onClick={finish}>Firmar contrato</button></>}
{deal.stage==='failed'&&<><h3>Negociación rota</h3><div className="negotiation-message negative">{deal.clubMessage||deal.playerMessage}</div><p>El jugador seguirá en el mercado, pero este intento ha terminado.</p><button className="primary wide" onClick={()=>setDeal(null)}>Cerrar</button></>}</div></div></div>}</>}
