import React from 'react';import {Initials,Pill} from './UI.jsx';import {money} from '../game/engine.js';
const categoryLabels={sport:'Deportivo',club:'Club y directiva',business:'Negocio',infrastructure:'Infraestructura'};
const tabs={
 sport:[['dashboard','Inicio'],['squad','Plantilla'],['coach','Entrenador & táctica'],['transfers','Fichajes'],['competitions','Competiciones']],
 club:[['dashboard','Inicio'],['staff','Personal'],['board','Directiva'],['gm','Mi carrera']],
 business:[['business','Resumen'],['sponsors','Patrocinios'],['merch','Merchandising'],['hospitality','Hospitality & eventos'],['media','Media & miembros'],['suppliers','Operaciones'],['finance','Finanzas']],
 infrastructure:[['infrastructure','Master plan'],['stadium','Estadio'],['tickets','Tickets & abonos'],['clubFacilities','Instalaciones club'],['sportFacilities','Ciudad deportiva']],
};
export default function Shell({game,screen,setScreen,category,setCategory,onAdvance,onReset,children}){const position=game.table.findIndex(x=>x.id===game.club.id)+1;return <div className="app-shell"><header className="topbar"><button className="club-brand" onClick={()=>{setScreen('dashboard');setCategory(null)}}><Initials name={game.club.name}/><div><b>{game.club.name}</b><span>Despacho del Director General · Temporada {game.season}</span></div></button><div className="top-kpis"><span><small>Jornada</small><b>{Math.min(game.week,38)}/38</b></span><span><small>Posición</small><b>{position||'—'}º</b></span><span><small>Caja</small><b>{money(game.cash)}</b></span><span><small>Marca</small><b>{game.brandScore||'—'}</b></span><span><small>Directiva</small><b>{Math.round(game.boardConfidence)}%</b></span></div><div className="top-actions"><Pill>{game.dateLabel}</Pill><button className="advance" onClick={onAdvance} disabled={game.week>38}>Avanzar semana ▶</button></div></header>{category&&<nav className="subnav" aria-label={categoryLabels[category]}><button className="subnav-title" onClick={()=>{setCategory(null);setScreen('dashboard')}}>← {categoryLabels[category]}</button>{tabs[category].map(([id,label])=><button key={id} className={screen===id?'active':''} onClick={()=>setScreen(id)}>{label}</button>)}<button className="reset-link" onClick={onReset}>Nueva partida</button></nav>}<main className="content">{children}</main></div>}
