import {clubs,primeraFederacionClubs} from '../src/data/clubs.js';
import {advanceWeek,buildCommercialUnit,createGame,evaluateClubOffer,getActiveTactic,getFanTacticalSatisfaction,playerTacticalFit,produceMerch,stadiumUpgrade} from '../src/game/engine.js';
const club=primeraFederacionClubs[0];
const game=createGame(club,{name:'QA GM',archetype:'business',salary:90000,stats:{finance:10,players:8,fans:6,board:8,football:5,tactics:4,commercial:10}});
if(clubs.length!==100)throw new Error(`Expected 100 clubs, got ${clubs.length}`);
if(primeraFederacionClubs.length!==40)throw new Error(`Expected 40 Primera Federación clubs, got ${primeraFederacionClubs.length}`);
if(game.players.length<22||game.schedule.length!==38)throw new Error('Universe generation failed');
if(!getActiveTactic(game)?.formation)throw new Error('Coach tactic missing');
const fit=playerTacticalFit(game.players[0],getActiveTactic(game));if(fit<0||fit>100)throw new Error('Player tactical fit invalid');
const fanFit=getFanTacticalSatisfaction(game);if(fanFit<0||fanFit>100)throw new Error('Fan tactical fit invalid');
const stocked=produceMerch(game,'shirt',100);if(stocked.merch.inventory.shirt!==100)throw new Error('Merch production failed');
const upgraded=stadiumUpgrade({...stocked,cash:stocked.cash+1000000},'barcode');if(upgraded.stadium.access==='Manual')throw new Error('Stadium access upgrade failed');
const built=buildCommercialUnit(upgraded,1,'rental');if(built.stadium.units.length<2)throw new Error('Commercial unit build failed');
const target=game.market.find(p=>p.club!=='Libre');const negotiation=evaluateClubOffer(game,target,target.seller.asking,1);if(negotiation.status!=='accepted')throw new Error('Transfer negotiation evaluation failed');
const next=advanceWeek(game);if(next.week!==2||!next.lastMatch)throw new Error('Weekly simulation failed');
if(next.table.reduce((s,r)=>s+r.p,0)!==20)throw new Error('League table simulation failed');
console.log('Smoke tests passed',{clubs:clubs.length,primeraFederacion:primeraFederacionClubs.length,players:game.players.length,schedule:game.schedule.length,tacticalFit:fit,fanFit});
