import {clubs,primeraFederacionClubs} from '../src/data/clubs.js';
import {advanceWeek,createGame,evaluateClubOffer,facilityBonuses,getActiveTactic,getFanTacticalSatisfaction,playerTacticalFit,produceMerch,startFacilityProject,ticketProjection,upgradeMerchChannel,coachIntervene,leaseCommercialUnit} from '../src/game/engine.js';
const club=primeraFederacionClubs.find(c=>c.name==='CD Lugo')||primeraFederacionClubs[0];
const gm={name:'QA GM',archetype:'business',salary:90000,stats:{finance:10,players:8,fans:6,board:8,football:7,tactics:7,commercial:10}};
let game=createGame(club,gm);
if(clubs.length!==100)throw new Error(`Expected 100 clubs, got ${clubs.length}`);
if(primeraFederacionClubs.length!==40)throw new Error(`Expected 40 Primera Federación clubs, got ${primeraFederacionClubs.length}`);
if(game.players.length<22||game.schedule.length!==38)throw new Error('Universe generation failed');
if(game.version!==3)throw new Error('Expected v3 game state');
if(game.sponsorOffers.some(x=>x.scope==='global'||x.scope==='national'))throw new Error('1RFEF received ineligible large sponsor');
const fit=playerTacticalFit(game.players[0],getActiveTactic(game));if(fit<0||fit>100)throw new Error('Player tactical fit invalid');
const fanFit=getFanTacticalSatisfaction(game);if(fanFit<0||fanFit>100)throw new Error('Fan tactical fit invalid');
const tp=ticketProjection(game);if(tp.attendance<0||tp.attendance>game.stadium.capacity)throw new Error('Ticket projection invalid');
const stocked=produceMerch(game,'shirt',100);if(stocked.merch.inventory.shirt!==100)throw new Error('Merch production failed');
const channel=upgradeMerchChannel({...stocked,cash:stocked.cash+100000},'ecommerce');if(channel.merch.channels.ecommerce!==1)throw new Error('Merch channel upgrade failed');
let project=startFacilityProject({...channel,cash:channel.cash+500000},'stadium','scoreboard');if(project.infrastructure.projects.length!==1)throw new Error('Facility project failed to start');
for(let i=0;i<3;i++)project=advanceWeek(project);if(project.infrastructure.levels.stadium.scoreboard!==1)throw new Error('Facility project failed to complete');
if((facilityBonuses(project).fan||0)<2)throw new Error('Facility bonuses not applied');
const leased=leaseCommercialUnit({...project,cash:project.cash+100000},0,'kiosk');if((leased.stadium.units||[]).length!==1)throw new Error('Commercial-unit leasing failed');
const before=project.coachRelationship.interventions;const intervened=coachIntervene(project,'attack',false);if(intervened.coachRelationship.interventions!==before+1)throw new Error('Coach interaction failed');
const target=game.market.find(p=>p.club!=='Libre');const negotiation=evaluateClubOffer(game,target,target.seller.asking,1);if(negotiation.status!=='accepted')throw new Error('Transfer negotiation evaluation failed');
const next=advanceWeek(game);if(next.week!==2||!next.lastMatch)throw new Error('Weekly simulation failed');
if(next.table.reduce((s,r)=>s+r.p,0)!==20)throw new Error('League table simulation failed');
console.log('Smoke tests passed',{clubs:clubs.length,primeraFederacion:primeraFederacionClubs.length,brand:game.brandScore,tacticalFit:fit,fanFit,attendance:tp.attendance,sponsorScopes:[...new Set(game.sponsorOffers.map(x=>x.scope))]});
