import React,{useEffect,useState} from 'react';
import StartFlow from './components/StartFlow.jsx';import Shell from './components/Shell.jsx';
import Dashboard from './screens/Dashboard.jsx';import Squad from './screens/Squad.jsx';import Coach from './screens/Coach.jsx';import Transfers from './screens/Transfers.jsx';import Competitions from './screens/Competitions.jsx';import Staff from './screens/Staff.jsx';import Board from './screens/Board.jsx';import GM from './screens/GM.jsx';import Suppliers from './screens/Suppliers.jsx';
import FinanceV3 from './screens/FinanceV3.jsx';import TicketingV3 from './screens/TicketingV3.jsx';
import {BusinessOverview,SponsorsV3,MerchV3,HospitalityV3,MediaV3} from './screens/BusinessV3.jsx';
import {InfrastructureOverview,StadiumV3,ClubFacilities,SportFacilities} from './screens/Infrastructure.jsx';
import {acceptSponsor,advanceWeek,applyTacticalPreset,completeTransfer,createGame,evaluateClubOffer,evaluatePlayerOffer,hireStaff,produceMerch,setTactic,signSupplier,submitSponsorOffer,startFacilityProject,updateTicketZone,upgradeMerchChannel,setMerchPrice,setBusinessPolicy,coachIntervene,fireCoach,leaseCommercialUnit} from './game/engine.js';
const SAVE_KEY='football-director-poc-v3';
export default function App(){
  const [game,setGame]=useState(()=>{try{return JSON.parse(localStorage.getItem(SAVE_KEY))||null}catch{return null}});const [screen,setScreen]=useState('dashboard');const [category,setCategory]=useState(null);
  useEffect(()=>{if(game)localStorage.setItem(SAVE_KEY,JSON.stringify(game));},[game]);
  if(!game)return <StartFlow onStart={(club,gm)=>setGame(createGame(club,gm))}/>;
  const openCategory=(cat)=>{setCategory(cat);setScreen(cat==='sport'?'coach':cat==='club'?'staff':cat==='business'?'business':'infrastructure')};
  const reset=()=>{localStorage.removeItem(SAVE_KEY);setGame(null);setScreen('dashboard');setCategory(null)};const props={game,setGame};let content=<Dashboard game={game} onOpen={openCategory} setScreen={setScreen}/>;
  if(screen==='squad')content=<Squad {...props}/>;
  if(screen==='coach')content=<Coach {...props} hire={(r,c)=>setGame(hireStaff(game,r,c))} setTactic={(p)=>setGame(setTactic(game,p))} preset={(id)=>setGame(applyTacticalPreset(game,id))} intervene={(id,force)=>setGame(coachIntervene(game,id,force))} fire={()=>setGame(fireCoach(game))}/>;
  if(screen==='transfers')content=<Transfers {...props} evaluateClub={(p,a,r)=>evaluateClubOffer(game,p,a,r)} evaluatePlayer={(p,s,b,r)=>evaluatePlayerOffer(game,p,s,b,r)} complete={(p,f,s,b)=>setGame(completeTransfer(game,p,f,s,b))}/>;
  if(screen==='competitions')content=<Competitions {...props}/>;if(screen==='staff')content=<Staff {...props} hire={(r,c)=>setGame(hireStaff(game,r,c))}/>;if(screen==='board')content=<Board {...props}/>;if(screen==='gm')content=<GM {...props}/>;
  if(screen==='business')content=<BusinessOverview {...props} setScreen={setScreen}/>;
  if(screen==='sponsors')content=<SponsorsV3 {...props} accept={(s)=>setGame(acceptSponsor(game,s))} submit={(s,a)=>submitSponsorOffer(game,s,a)}/>;
  if(screen==='merch')content=<MerchV3 {...props} produce={(k,q)=>setGame(produceMerch(game,k,q))} upgradeChannel={(k)=>setGame(upgradeMerchChannel(game,k))} setPrice={(k,p)=>setGame(setMerchPrice(game,k,p))}/>;
  if(screen==='hospitality')content=<HospitalityV3 {...props} setPolicy={(a,p)=>setGame(setBusinessPolicy(game,a,p))}/>;
  if(screen==='media')content=<MediaV3 {...props} setPolicy={(a,p)=>setGame(setBusinessPolicy(game,a,p))}/>;
  if(screen==='suppliers')content=<Suppliers {...props} sign={(cat,c)=>setGame(signSupplier(game,cat,c))}/>;
  if(screen==='finance')content=<FinanceV3 {...props}/>;
  if(screen==='infrastructure')content=<InfrastructureOverview {...props} setScreen={setScreen}/>;
  const build=(g,id)=>setGame(startFacilityProject(game,g,id));
  if(screen==='stadium')content=<StadiumV3 {...props} onBuild={build} onUnit={(slot,type)=>setGame(leaseCommercialUnit(game,slot,type))}/>;
  if(screen==='tickets')content=<TicketingV3 {...props} updateZone={(z,p)=>setGame(updateTicketZone(game,z,p))}/>;
  if(screen==='clubFacilities')content=<ClubFacilities {...props} onBuild={build}/>;
  if(screen==='sportFacilities')content=<SportFacilities {...props} onBuild={build}/>;
  return <Shell game={game} screen={screen} setScreen={setScreen} category={category} setCategory={setCategory} onAdvance={()=>setGame(advanceWeek(game))} onReset={reset}>{content}</Shell>;
}
